### ISSUE TITLE
Can't access Chinese variable

### ISSUE THREAD

**Issue by nluyan** [Samsung/netcoredbg#10]
if Chinese named variable in code,  it will not access the value by use -var-create command in GDB.

**Comment by ayuckhulk** [comment]
@nluyan Hello, sorry for late response. Could you please specify more details:
1. On which platform do you run the `netcoredbg` binary?
2. Please provide code example with Chinese named variable which does not work.

Thanks!

**Comment by nluyan** [comment]
Thanks for reply.

I run netcoredbg on Windows 10 Chinese version. and .net core 2.2
this is my test code:

using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            int a = 32;
            double b = 63.35;
            string 测试 = "电视机";  //Chinese named variable
            DateTime time = DateTime.Now;
            Console.WriteLine("End");
        }
    }
}

 
debug command:
-file-exec-and-symbols dotnet
-exec-arguments ~\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp2.2\ConsoleApp2.dll
-break-insert -f Program.cs:14
-exec-run
-exec-continue
-var-create - * "测试"

result:
![image](https://user-images.githubusercontent.com/19815268/51579203-0f126880-1efb-11e9-89d8-64edf6ab7df0.png)

It looks like an encoding problem, often happens on GB2312 <==> UTF8

**Comment by ayuckhulk** [comment]
@nluyan Please try the latest build and see if it works for your case.

**Comment by jeanjvv12** [comment]
cordova plugin add instabug-cordova

**Comment by ayuckhulk** [comment]
I close this issue since there is no more feedback.

**Comment by jeanjvv12** [comment]
Yes binary is ok but .txt and some word docs have a bug. Utf8 Not your fault . Md5 ssh is older but tokens and dockers two step verification is pretty tight locks .
