### ISSUE TITLE
M1 ARM Support?

### ISSUE THREAD

**Issue by PhantomCloak** [Samsung/netcoredbg#102]
This issue is an extension of #98 which closed by author as workaround discovered, problem is x64 OSX build does not work with ARM OmniSharp and turns out OmniSharp itself also should be the same architecture as netcoredbg well as dotnet, using rosetta looks like a manageable solution but performance hit grows as project gotten bigger for example when I use netcoredbg I had to setup env vars to run x64 OmniSharp + Dotnet with same setup I also need to work with unity which tends to be more demanding than average web application and so loading times can exceed 140seconds compared to 30-45 seconds with ARM build, so I'm wondering is that problem can be solved without workaround or will it be?

**Comment by viewizard** [comment]
This problem can be solved only with netcoredbg built for M1. You probably could try build it on your Mac, since we support Linux aarch64, but I can't guaranty that you can build it successfully.

The main issue is - we have Mac Mini with x64 cpu only now in our CI, so, we could build and support x64 binary only. Just believe me, that was not so easy argue why we (our project) need Mac Mini x64 for our CI, not sure when we will have Mac Mini M1 version.

Note, netcoredbg initially was aimed to debug .Net applications on Tizen OS (debugger is part of Tizen Studio, https://developer.tizen.org/), Windows/Linux/Mac OSes support is not our main goal (at least at work time :-).

**Comment by PhantomCloak** [comment]
Thanks for the explanation it's sounds fair, so I will keep this issue open for few days and try to build and run on my M1 machine if it succeed I'm gonna fork it or just paste the build here, if sounds good

**Comment by alpencolt** [comment]
@PhantomCloak if you will succeed with M1 build you can open PR there, we're open for contribution.

**Comment by matthewblott** [comment]
I just tried to build this on my M1 Macbook. It compiled okay but then ```make install``` threw an error:

```bash
INSERT ❯ make install
[  1%] Building CXX object third_party/linenoise-ng/CMakeFiles/linenoise.dir/src/ConvertUTF.cpp.o
clang: warning: argument unused during compilation: '-force_flat_namespace' [-Wunused-command-line-argument]
[  2%] Building CXX object third_party/linenoise-ng/CMakeFiles/linenoise.dir/src/linenoise.cpp.o
clang: warning: argument unused during compilation: '-force_flat_namespace' [-Wunused-command-line-argument]
[  3%] Building CXX object third_party/linenoise-ng/CMakeFiles/linenoise.dir/src/wcwidth.cpp.o
clang: warning: argument unused during compilation: '-force_flat_namespace' [-Wunused-command-line-argument]
[  4%] Linking CXX static library liblinenoise.a
[  4%] Built target linenoise
[  5%] Building C object third_party/linenoise-ng/CMakeFiles/example.dir/tst/example.c.o
[  7%] Linking CXX executable example
[  7%] Built target example
[  8%] Building CXX object src/CMakeFiles/corguids.dir/__/.coreclr/src/pal/prebuilt/idl/clrdata_i.cpp.o
clang: warning: argument unused during compilation: '-force_flat_namespace' [-Wunused-command-line-argument]
In file included from /Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/prebuilt/idl/clrdata_i.cpp:23:
In file included from /Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/inc/rt/rpc.h:16:
In file included from /Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/inc/rt/palrt.h:137:
/Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/inc/pal.h:2518:2: warning:  [-W#warnings]
#warning
 ^
/Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/inc/pal.h:2519:2: error: PAL_CS_NATIVE_DATA_SIZE is not defined for this architecture
#error  PAL_CS_NATIVE_DATA_SIZE is not defined for this architecture
 ^
/Users/Matt/Develop/lab/netcoredbg/.coreclr/src/pal/inc/pal.h:2535:34: error: use of undeclared identifier 'PAL_CS_NATIVE_DATA_SIZE'
        BYTE rgNativeDataStorage[PAL_CS_NATIVE_DATA_SIZE];
                                 ^
1 warning and 2 errors generated.
make[2]: *** [src/CMakeFiles/corguids.dir/__/.coreclr/src/pal/prebuilt/idl/clrdata_i.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/corguids.dir/all] Error 2
make: *** [all] Error 2

```

Any ideas?

**Comment by codeprefect** [comment]
@PhantomCloak, there is now a native M1 build [here](https://github.com/codeprefect/netcoredbg/releases/tag/2.2.0-950).
Please test it out and let us know if it works.

**Comment by PhantomCloak** [comment]
> @PhantomCloak, there is now a native M1 build [here](https://github.com/codeprefect/netcoredbg/releases/tag/2.2.0-950). Please test it out and let us know if it works.

Thanks I'm gonna start to use as part of my daily driver in this week, I will update after testing on some existing projects that I wish to use on it

**Comment by gbalykov** [comment]
MacOS arm64 architecture support is added now as community supported architecture, because we are not able to test it. You can build netcoredbg for MacOS arm64 from latest sources.

**Comment by Cliffback** [comment]
Hi. I came over this thread while searching for this issue, and ended up compiling my own version as well as creating a plugin for easy integration with Neovim DAP, so if anyone is interested, you can find it here:
[https://github.com/Cliffback/netcoredbg-macOS-arm64.nvim](https://github.com/Cliffback/netcoredbg-macOS-arm64.nvim)

**Comment by Cliffback** [comment]
Just updated my build to the latest version. Have put this repo on a watchlist, so I should get notifications when new releases are added. I'll try to keep it up to date.
