### ISSUE TITLE
[Bug] Missing field from Scopes response

### ISSUE THREAD

**Issue by filipdutescu** [Samsung/netcoredbg#104]
## Problem description

I am trying to use `netcoredbg` in the VSCode interpreter mode to debug some .NET projects. While for the most part I am able to do this in my preferred editor, I find that there is a problem with Scopes request. The received response is missing the `Scope.expensive` field, making it an invalid response in the eyes of the editor.

## Expected behaviour

According to [the specificiation](https://microsoft.github.io/debug-adapter-protocol/specification), the `Scope` type has a required `boolean` field called `expensive` which must be present:

```ts
interface Scope {
  // ...

  /**
   * If true, the number of variables in this scope is large or expensive to
   * retrieve.
   */
  expensive: boolean;

  // ...
}
```

I expected the DAP server response to contain it, as such:

```
-> REQ {"type":"request","seq":7,"command":"scopes","arguments":{"frameId":0}}
<- RESP {"body":{"scopes":[{"name":"Locals","namedVariables":2,"variablesReference":1,"expensive":false}]},"command":"scopes","request_seq":7,"seq":"21","success":true,"type":"response"}
```

## Actual behaviour

The response does not actually have the field, leading to an editor debugging error, preventing me from seeing variables in debug sessions:

```
-> REQ {"type":"request","seq":7,"command":"scopes","arguments":{"frameId":0}}
<- RESP {"body":{"scopes":[{"name":"Locals","namedVariables":2,"variablesReference":1}]},"command":"scopes","request_seq":7,"seq":"21","success":true,"type":"response"}
```

**Comment by viewizard** [comment]
Thank you for your help, here is the fix, will be in next release:
```
From 3c802d59dd816b22e3294f7fc5f7a61f9e049ebc Mon Sep 17 00:00:00 2001
From: Mikhail Kurinnoi <m.kurinnoi@samsung.com>
Date: Tue, 13 Sep 2022 17:04:16 +0300
Subject: [PATCH] Fix VSCode protocol `scopes` command, add `expensive` field.

---
 src/protocols/vscodeprotocol.cpp | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/protocols/vscodeprotocol.cpp b/src/protocols/vscodeprotocol.cpp
index 4b8aa5b..031f0ae 100644
--- a/src/protocols/vscodeprotocol.cpp
+++ b/src/protocols/vscodeprotocol.cpp
@@ -96,7 +96,8 @@ void to_json(json &j, const Thread &t) {
 void to_json(json &j, const Scope &s) {
     j = json{
         {"name",               s.name},
-        {"variablesReference", s.variablesReference}};
+        {"variablesReference", s.variablesReference},
+        {"expensive",          false}};
 
     if (s.variablesReference > 0)
     {
-- 
2.25.1
```
note, in netcoredbg case, `expensive` field will be `false` all the time.

**Comment by filipdutescu** [comment]
Thanks for the quick reply and for fixing it so rapidly @viewizard! Looking forward to use this improvement moving forward! Have a wonderful day!

**Comment by filipdutescu** [comment]
Is there anywhere I can see the release schedule? Or is it at fixed time intervals?

**Comment by viewizard** [comment]
Usually I am just coding, have not time for release scheduling, @alpencolt care about this. :-)
@alpencolt what next sync/release date you have planned?

**Comment by alpencolt** [comment]
There is no strict schedule for public releases, but I think we can sync up this week  after testing

**Comment by viewizard** [comment]
Fixed in new release, please, check.

**Comment by filipdutescu** [comment]
All works wonderfully, thank you a lot for your quick responses, fix and release! :rocket: I will close the issue as fixed.
