### ISSUE TITLE
Debugging embedded assemblies

### ISSUE THREAD

**Issue by rogerfar** [Samsung/netcoredbg#109]
I have been playing with netcoredbg for a big and it works nicely for our .NET 6 application, but I am wondering if something is possible.

Our application has a built in monaco editor where users can write C# code, this C# gets compiled to a DLL and can be ran on the same application. The app loads the DLL and executes it with certain parameters. The application is built in release mode, but the DLL's are built in debug mode, so I am exploring options to see if we can add breakpoint support for those DLL's.

Currently the DLL's are loaded as an assembly:

```
        var fileBytes = File.ReadAllBytes(filePath);
        var pdbBytes = File.ReadAllBytes(pdbPath);

        var assembly = Assembly.Load(fileBytes, pdbBytes);
        var type = assembly.GetType("Main");

        var result= executionObject.Type.InvokeMember("Method", params);
```

Is it possible to attach netcoredbg to the main process and add breakpoints to the dynamically loaded DLL's? Or might there be a different way to add debug functionality?

**Comment by gbalykov** [comment]
You can try to use https://github.com/Samsung/netcoredbg/pull/108 PR. I've not tested it myself yet, but it seems to handle exactly your case. 

Regarding debug of release dlls (if pdbs are present), you need to disable just-my-code. Here's an example on how to do this with cli interface: https://github.com/Samsung/netcoredbg/blob/master/doc/cli.md#debugging-release-build-of-dlls. After this breakpoints are successfully set and hit.

**Comment by rogerfar** [comment]
I'm not sure why I didn't see #91 , that's exactly the use case I have here!
