### ISSUE TITLE
netcoredbg on monodevelop

### ISSUE THREAD

**Issue by rafael-neri** [Samsung/netcoredbg#11]
Is it possible to use on monodevelop?
If yes, how to configure?

**Comment by ayuckhulk** [comment]
@rafael-neri It looks like MonoDevelop does not support adding external debuggers without writing an extension. And there is no such extesion :disappointed: currently available (or could not find it).
So I guess you can not use netcoredbg with MonoDevelop at the moment.

**Comment by lextm** [comment]
I did a prototype of such an extension but there are certain bugs (will report them in the coming weeks) on MonoDevelop side that prevent the prototype from working reliably.

Once everything starts to work, we will revisit and see if that extension should live in its own repo, or here, or under MonoDevelop.

**Comment by lextm** [comment]
So here is an update on my experiments.

This debugger does have some behavior differences (#19 and #20) from vsdbg, which requires changes, such as #21 and #22.

I think #21 can be merged, while #22 is just some hack I used to assert feasibility, and might not reach the quality.

Once both issues are resolved, then it is quite easy to write a MonoDevelop extension, based on its existing code base and other examples. I have a prototype at hand, but of course its quality is quite low. 

Hope #19 and #20 can be fixed soon, and then I can extend the prototype to a reliable extension for everyone.

**Comment by lextm** [comment]
@ayuckhulk can you reopen this issue, so that we can track the progress here (before the extension becomes a reality itself).
