### ISSUE TITLE
Failed command 'configurationDone':0x80131c3c

### ISSUE THREAD

**Issue by akorchev** [Samsung/netcoredbg#111]
Hi,

I have a weird issue which I don't know how to solve. It happens on a user machine (MacBook Pro, M1) which is identical to mine where this error doesn't happen. Debugging fails with 0x80131c3c which according to another issue indicates that dbgshim fails to load. Here is the complete log:

```
[2023-02-28 07:41:09.267] [info]  [DebugAdapterClient] sending request 'initialize' (5) {
  "adapterID": ""
}
[2023-02-28 07:41:09.271] [info]  [DebugAdapterClient] Received event 'capabilities' (1) {
  "body": {
    "capabilities": {
      "exceptionBreakpointFilters": [
        {
          "filter": "user-unhandled",
          "label": "user-unhandled"
        },
        {
          "filter": "all",
          "label": "all"
        }
      ],
      "supportTerminateDebuggee": true,
      "supportsCancelRequest": true,
      "supportsConditionalBreakpoints": true,
      "supportsConfigurationDoneRequest": true,
      "supportsExceptionFilterOptions": true,
      "supportsExceptionInfoRequest": true,
      "supportsExceptionOptions": false,
      "supportsFunctionBreakpoints": true,
      "supportsSetExpression": true,
      "supportsSetVariable": true,
      "supportsTerminateRequest": true
    }
  },
  "event": "capabilities",
  "seq": "1",
  "type": "event"
}
[2023-02-28 07:41:09.272] [info]  [DebugAdapterClient] Received event 'initialized' (2) {
  "body": {},
  "event": "initialized",
  "seq": "2",
  "type": "event"
}
[2023-02-28 07:41:09.272] [info]  [DebugAdapterClient] received response for 'initialize' (5) {
  "body": {
    "exceptionBreakpointFilters": [
      {
        "filter": "user-unhandled",
        "label": "user-unhandled"
      },
      {
        "filter": "all",
        "label": "all"
      }
    ],
    "supportTerminateDebuggee": true,
    "supportsCancelRequest": true,
    "supportsConditionalBreakpoints": true,
    "supportsConfigurationDoneRequest": true,
    "supportsExceptionFilterOptions": true,
    "supportsExceptionInfoRequest": true,
    "supportsExceptionOptions": false,
    "supportsFunctionBreakpoints": true,
    "supportsSetExpression": true,
    "supportsSetVariable": true,
    "supportsTerminateRequest": true
  },
  "command": "initialize",
  "request_seq": 5,
  "seq": "3",
  "success": true,
  "type": "response"
}
[2023-02-28 07:41:09.272] [info]  [DebugAdapterClient] sending request 'attach' (6) {
  "processId": 2789
}
[2023-02-28 07:41:09.272] [info]  [DebugAdapterClient] received response for 'attach' (6) {
  "body": {},
  "command": "attach",
  "request_seq": 6,
  "seq": "4",
  "success": true,
  "type": "response"
}
[2023-02-28 07:41:09.273] [info]  [DebugAdapterClient] sending request 'configurationDone' (7)
[2023-02-28 07:41:09.412] [info]  [DebugAdapterClient] received error response for 'configurationDone' (7) {
  "command": "configurationDone",
  "message": "Failed command 'configurationDone' : 0x80131c3c",
  "request_seq": 7,
  "seq": "5",
  "success": false,
  "type": "response"
}
```

Some background. I have successfully built netcoredbg for Mac M1 by following #103 - everything works fine on three different M1 macs that I have access to. I am sure I am bundling `libdbgshim.dylib` from the DbgShim nuget package (using the latest version 7.0.410101). I have also requested the user to show me the log of `dotnet --info` and it seems he has the arm64 version of .NET framework 7 installed. Everything is exactly the same as my system - macOS version, .NET version etc. Does this error happen in cases that are different than dbgshim mismatch? Any other tips how to troubleshoot this further?

**Comment by akorchev** [comment]
Yes, it is and [IDE](https://www.radzen.com/blazor-studio) that we make. We launch netcoredbg as a process (`netcoredbg --interpreter=vscode`) and send DAP commands. Works in every other case so launching shouldn't be the cause of the problem.

**Comment by viewizard** [comment]
https://github.com/Samsung/netcoredbg/issues/98

**Comment by gbalykov** [comment]
@akorchev check that all libraries and binaries (e.g. dotnet sdk, dbgshim, netcoredbg) that you use are for osx-arm64, not osx-amd64. Looks like you have some osx-amd64 lib. See https://github.com/Samsung/netcoredbg/issues/98#issuecomment-1167349916 for more details.

**Comment by akorchev** [comment]
@viewizard yes, the error message is the same however I have built netcoredbg for macos arm64 and have it running on multiple machines. It is only one user (so far) that is reporting this problem. Hence this issue.

**Comment by gbalykov** [comment]
How are apps launched? Can 6.0 osx-amd64 sdk be used for some reason?

**Comment by akorchev** [comment]
I asked the user to add this code to their app (which is started with `dotnet run` and then debugged)

```
Console.WriteLine($".NET {Environment.Version} {System.Runtime.InteropServices.RuntimeInformation.OSDescription} {System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture}");
```

The output he got was this:

```
.NET 7.0.3 Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 Arm64
```

which makes me think the .NET SDK being used is for arm64. 

Anything else I could try? Some more detailed logging that I could enable in `netcoredbg` ?

**Comment by gbalykov** [comment]
You can try smth like strace to track all loaded libraries, but not sure whether it's available for mac or not.

**Comment by akorchev** [comment]
The error seems to be CORDBG_E_DEBUG_COMPONENT_MISSING which means libmscordbi.dylib or libmscordaccore.dylib can't be found or loaded. Do you know if some environment variable could interfere with finding those files?

**Comment by akorchev** [comment]
After a lot of trial and error it turned out to be an issue caused by the macOS hardened runtime. Loading libraries requires this to be included in the plist when signing your application:

```
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
```

Hopefully this would help someone.
