### ISSUE TITLE
list command does not do anything

### ISSUE THREAD

**Issue by isbobbydigitalak** [Samsung/netcoredbg#112]
Hello when running netcoredbg in CLI mode, when using the `list` command or the abbreviation `l` nothing actually gets printed for me. This is despite compiling with `<EmbedAllSources>true</EmbedAllSources>` as specified in the CLI manual. I'm running the latest version of netcoredbg on debian. Have tried on both .net 6 and .net 7 projects but can't get it to print source code.

Any ideas?

**Comment by gbalykov** [comment]
Please share more details on how you build netcoredbg and how you launch debug session.

**Comment by isbobbydigitalak** [comment]
I did not build netcoredbg, I downloaded it from the releases on this github. Is it better to build it from source perhaps?

As for launching I run `netcoredbg --interpreter=cli -- dotnet bin/Debug/net7.0/Example.dll`

Then I'll simply set a breakpoint like `b Program.cs:3` and run `r`, and then try to run `l` which gives me strange output like:

``` 
ncdb> l
   1	��B
``` 

What about the environment would you like to know? I guess I should specify that it's on debian bookworm (testing).

**Comment by gbalykov** [comment]
Thanks for reporting this, there's a bug with small tests. We'll fix it and fix will be available on next sync with our internal repo. In the mean time, you can simply add one more `Console.WriteLine` to your test and it should work fine (i.e. problem is only with one line tests).

**Comment by isbobbydigitalak** [comment]
Hmm but I had the same issue when I tried to use the debugger on a much larger program, which was what I actually wanted to debug with netcoredbg.

Or actually, I'm not entirely convinced it is the same issue, since the example above prints some jumbled characters, whereas when I used it in other cases it might not print anything at all etc.

**Comment by gbalykov** [comment]
This should be fixed in latest release. Feel free to reopen if you see any more related issues.
