### ISSUE TITLE
New versions of NetCoreDbg consume high CPU usage while being in idle

### ISSUE THREAD

**Issue by alberto-carp** [Samsung/netcoredbg#114]
While upgrading from version [2.0.0-895](https://github.com/Samsung/netcoredbg/releases/tag/2.0.0-895)  to [2.0.0-915](https://github.com/Samsung/netcoredbg/releases/tag/2.0.0-915) I noticed a high CPU usage of NetCoreDbg, ( 20 % of my CPU) even for simple application while being stuck in a breakpoint. With previous version the usage was basically 0.
After a simple check in the source code, I noticed that it seems related with the changes that were introduced in the `iosystem.h` and  `iosystem_win32.cpp` once the  type `data_align_t` was added and used.
A simple workaround for me was to rebuild the latest sources without those changes ( introduced in  https://github.com/Samsung/netcoredbg/commit/21d84f2da69eb65fd2f69c60eb5fa41ed3d75603).
I'm working on Windows X64, and I use the NetCoreDbg  through the VSProtocol with a custom application as client, but I tested also the CLI interface and the usage it's the same.
Can we expect a fix, that solve the high CPU usage?

**Comment by gbalykov** [comment]
Have you checked latest source with those changes? Latest version is 2.2.0-961, maybe your problem is already fixed somewhere. It doesn't seem that `data_align_t` change can have any effect on cpu usage. Also please share your build command.

**Comment by gbalykov** [comment]
Can you try to revert parts of https://github.com/Samsung/netcoredbg/commit/21d84f2da69eb65fd2f69c60eb5fa41ed3d75603 separately? Maybe starting from file by file, then parts of one file, and so on. This way you'll be able to track exact change that led to strange behavior that you see.

**Comment by alberto-carp** [comment]
That what I've done to isolate the problem and find out that  the issue is somehow related with the files `iosystem_win32.cpp` and `iosystem.h` . For now my problem is solved since I only revert those files ( ~ 10-20 lines of code  and those files were not  changed since then) and rebuild manually. 
I was only asking if you plan to investigate the issue in the next release, since I would not want to manually rebuild the source and revert those changes on each official release.

**Comment by gbalykov** [comment]
We'll take a look at this issue, but currently I'm not sure when. I think next release will be until the end of march, and we won't have time to investigate this problem until then.

**Comment by gbalykov** [comment]
This should be fixed in latest release. Feel free to reopen if you see any more related issues.
