### ISSUE TITLE
line breakpoint did not work in vscode with netcoreapp3.0

### ISSUE THREAD

**Issue by itn3000** [Samsung/netcoredbg#12]
# Overview

I tried to use netcoredbg as vscode's debugger with dotnet sdk-3.0pre3.
I set breakpoint, but vscode did not stop at the breakpoint.

# Environment

* os: win8.1-x64
* vscode: 1.32.1
* csharp-extension: 1.17.1
* omnisharp: 1.32.12-beta9
* netcoredbg: download from [release page](https://github.com/Samsung/netcoredbg/releases)
* dotnetcore-sdk: 3.0.100-preview3-010431

# Steps to reproduce

1. creating new console project with `dotnet new console`
2. ensure `TargetFramework` to `netcoreapp3.0`
3. build program with `dotnet build`
4. add following setting in launch.json to use netcoredbg
5. set breakpoint at `Console.WriteLine`
6. launch vscode's debug session

launch.json setting is following;
```json
        {
            "name": ".NET Core Launch with netcoredbg",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/consolereadkeytest.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "cmd",
                "pipeArgs": ["/c"],
                "debuggerPath": "g:/bin/netcoredbg/netcoredbg.exe"
            }
        }

```

(fix "program" to point "netcoreapp3.0" directory)

# Expected Result

stop on `Console.WriteLine` and variables are displayed.

# Actual Result

program exited with code 0.

## Notes

* I also tried at `TargetFramwork` == `netcoreapp2.1` and `netcoreapp2.2`, breakpoint worked expectedly
* stop at unhandled exception was worked
* stop with pause button was worked

**Comment by ayuckhulk** [comment]
@itn3000 Thank you for the detailed report!
I was not able to reproduce this issue right away (I don't have win8 machine, but on win10 everything worked ok).
Could you please enable engine logging and post the output?
```
            ...
            "internalConsoleOptions": "openOnSessionStart",

            "logging": {
                "engineLogging": true
            },

            "pipeTransport": {
            ...
```

Also please enable debugger logs like this and attach them to this issue:
```
"debuggerPath": "g:/bin/netcoredbg/netcoredbg.exe --log=file"
```
(log files are created in `TEMP` folder, you can list them in PowerShell with `ls $env:temp\netcore*`)

**Comment by itn3000** [comment]
Thank you for replying, I made debug logs.
"netcoredbg-vscode-debugconsole.txt" is text from vscode's debug console.
[netcoredbg-logs.zip](https://github.com/Samsung/netcoredbg/files/2964234/netcoredbg-logs.zip)

**Comment by itn3000** [comment]
After my investigating, I found I misunderstood the point at issue.

It is not depended on netfm, but on filename case.
In windows, drive letter of filename in pdb is large case when build with `dotnet build`,
but small case when specified project path with small case(like `dotnet build c:\path\to\csproj`).
This causes the filename unmatch in `ResolveSequencePoint`.

I replaced following point to `x.Equals(y, StringComparison.OrdinalIgnoreCase)`, and found debugging works expectedly.

https://github.com/Samsung/netcoredbg/blob/4d5e6d70e28860ace26a1a67ae97b322a456f109/src/debug/netcoredbg/SymbolReader.cs#L257-L259

**Comment by ayuckhulk** [comment]
@itn3000 Wow, that's really great that you found a solution! Would you be so kind to create a pull request with the fix?

**Comment by itn3000** [comment]
I created PR as #16, please review it.

**Comment by smotti** [comment]
I still encounter issues with non-working breakpoints. The application is a ASP MVC (WebApi) app. Setting breakpoints using vsdbg work as expected.
Also `setExceptionsBreakpoints` fails, and I don't know why.

# Environment

Visual Code: 1.49.2
C# Extension: 1.23.2
Omnisharp: 1.37.1
netcoredbg: latest release build (Aug 20)
dotnet core sdk: 3.1.402
OS: Windows_NT x64 10.0.14393 (Windows Server 2016 Datacenter)

# Steps to reproduce

The same as OP. Including the debug launch config.

# Output

[netcoredb_vscode.log](https://github.com/Samsung/netcoredbg/files/5303490/netcoredb_vscode.log)

Unfortunately I don't really know where to start looking to help troubleshoot the issue further. So any guidance is appreciated.

Thank you!

**Comment by viewizard** [comment]
@smotti I updated netcoredbg sources, could you please check it?
If issue still here, please, open new issue instead.
