### ISSUE TITLE
Debugger does not work if add a breakpoint

### ISSUE THREAD

**Issue by svor** [Samsung/netcoredbg#13]
I tried to use netcoredbg with dotnet 2.2.104.
If I don't set breakpoints everything works fine, but if I add one or more breakpoint I'll get an error:
```gson
{ 
	command: 'threads',
  	message: 'Failed command \'threads\' : 0x80004005',
  	request_seq: 4,
  	seq: 6,
  	success: false,
  	type: 'response' 
}
```
### Environment

- os: Fedora 28 Twenty Eight (x86-64)
- dotnetcore-sdk: 2.2.104
- netcoredbg: [latest releas](https://github.com/Samsung/netcoredbg/releases/download/latest/netcoredbg-linux-master.tar.gz)

### Logs

netcoredbg's log file is here: https://raw.githubusercontent.com/svor/files/master/netcodedbg-launch.log

**Comment by ayuckhulk** [comment]
Hello @svor, thank you for reporting this issue.

It looks like your IDE did not send the `configurationDone` command. This command actually launches the process. Since there is no process the `threads` command fails.

netcoredbg's error messages surely need an improvement :smile:

**Comment by svor** [comment]
@ayuckhulk Thank you! I found the problem on my side and your information helped me)
Actually the problem was that I expected debug capabilities in initialize response, but it comes after `capabilities` event and the value of `capabilities` was overwritten.

**Comment by mickaelistria** [comment]
Good catch @svor . I think the current approach of not returning capabilities in initialize is an anti-pattern and doesn't fit very well in specification recommendation. I've open https://github.com/Samsung/netcoredbg/issues/14 to get it improved in netcoredbg.
