### ISSUE TITLE
Error on attach ... key 'processId' not found when trying attach neovim-dap debug adapter to netcoredbg

### ISSUE THREAD

**Issue by KaiWalter** [Samsung/netcoredbg#139]
Additional to a configuration where `netcoredbg` is started I want to have a configuration where I attached `neovim-dap` to the running debug server. For that I added a `coreclrattach` adapter and a corresponding `attach` configuration:

```
local dap, dapui = require("dap"), require("dapui")

dap.adapters.coreclr = {
  type = 'executable',
  command = '/usr/local/netcoredbg',
  args = { '--interpreter=vscode' },
}

dap.adapters.coreclrattach = {
  type = 'server',
  port = 4711,
}

dap.configurations.cs = {
  {
    type = "coreclr",
    name = "launch - netcoredbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to dll', vim.fn.getcwd() .. '/bin/Debug/', 'file')
    end,
  },
  {
    type = "coreclrattach",
    name = "attach - netcoredbg",
    request = "attach",
    pid = require('dap.utils').pick_process,
    args = {},
  },
}
```

In one shell session I start debugging with

```
/usr/local/netcoredbg --interpreter=vscode --server -- dotnet run -c Debug
```

and in the other session I start debugging with the `attach` configuration

```
Configuration:
1: launch - netcoredbg
2: attach - netcoredbg
Type number and <Enter> or click with the mouse (q or empty cancels): 2
```
with selecting the process to be debugged.

However attaching seems not to work and this error is raised:

```
Error on attach: can't parse: [json.exception.out_of_range.403] key 'processId' not found
```

log file `log.txt` imho bears no additional information:

```
9827.176 I/NETCOREDBG(P60708, T60708): main.cpp: main(431) > Netcoredbg started
9853.273 I/NETCOREDBG(P60708, T60708): main.cpp: instantiate_protocol(113) > Creating protocol VSCodeProtocol
9853.274 I/NETCOREDBG(P60708, T60708): main.cpp: main(475) > pidDebugee 0
9853.274 I/NETCOREDBG(P60708, T60832): ioredirect.cpp: worker(164) > worker started
9853.275 E/NETCOREDBG(P60708, T60836): vscodeprotocol.cpp: HandleCommandJSON(855) > JSON error: [json.exception.out_of_range.403] key 'processId' not found
9853.280 I/NETCOREDBG(P60708, T60708): vscodeprotocol.cpp: ReadData(872) > EOF
```

Is there a way to achieve this? What exactly is missing wrt to this error `key 'processId' not found`?

**Comment by viewizard** [comment]
In case of attach you should provide PID
1) as launch option (see netcoredbg launch options), but since `main.cpp: main(475) > pidDebugee 0` in your log, you didn't provide it;
2) as `processId` parameter of VSCode protocol attach request, but since `key 'processId' not found`  in your log, you (neovim-dap?) don't form request properly. VSCode attach request must have `processId` parameter.

**Comment by KaiWalter** [comment]
Thanks @viewizard - what I tried next:

In another [post](https://zignar.net/2023/02/17/debugging-neovim-with-neovim-and-nvim-dap/) I found, that `processId` is used instead of `pid` - which I took from this [cookbook](https://github.com/mfussenegger/nvim-dap/wiki/Cookbook#pick-a-process).

Hence I adapted my configuration to

```
  {
    type = "coreclrattach",
    name = "attach - netcoredbg",
    request = "attach",
    processId = require('dap.utils').pick_process,
    args = {},
  },
```

repeated to start the debugging session, but got

```
Failed command 'configurationDone' : 0x80070057
```

**Comment by viewizard** [comment]
`0x80070057` mean `E_INVALIDARG`.\
In case of VSCode protocol `configurationDone` request start debuggee session with all previously provided parameters (run process with provided path or attach to provided PID). In case of attach, for example, `0x80070057` error could mean you provide PID for not managed process (process that don't have `libcoreclr.so` in memory map):
https://github.com/Samsung/netcoredbg/blob/bac8ea845dc5484218b88ecf015abf81e6ef95d2/src/debugger/manageddebugger.cpp#L804-L805

**Comment by KaiWalter** [comment]
@viewizard thanks for the additional input - this made me rethink my approach.

I confused how to wire up NeoVim/DAP with netcoredbg - I tried to attach to netcoredbg instead of starting netcoredbg which then attaches to the debuggee.

This is my working configuration:

```
local dap, dapui = require("dap"), require("dapui")

-- dap.set_log_level('DEBUG')

dap.adapters.coreclr = {
  type = 'executable',
  command = '/usr/local/netcoredbg',
  args = { '--interpreter=vscode' },
}

dap.configurations.cs = {
  {
    type = "coreclr",
    name = "launch - netcoredbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to dll', vim.fn.getcwd() .. '/bin/Debug/', 'file')
    end,
  },
  {
    type = "coreclr",
    name = "attach - netcoredbg",
    request = "attach",
    processId = require('dap.utils').pick_process,
  },
}

dapui.setup()
```

**Comment by GustavEikaas** [comment]
@KaiWalter Did you ever get the attach to work properly? I am able to successfully run the debug adapter with coreclr as executable but when running netcoredbg on the dll directly. .Net user-secrets are not loaded in without extra hassle. I have tried a bunch of different configurations but cannot get the attach to work properly.

**Comment by KaiWalter** [comment]
@GustavEikaas this version worked for me at least in an **Azure Functions** environment: <https://github.com/KaiWalter/azure-functions.nvim/blob/main/lua/azure-functions.lua>. Maybe you can extract something out of it. I did not dive deeper into **netcoredbg** for that matter.

**Comment by GustavEikaas** [comment]
Thank you so much! Ill dig into it!
