### ISSUE TITLE
Can't hit breakpoint in asp.net core web application

### ISSUE THREAD

**Issue by lem102** [Samsung/netcoredbg#145]
Using the cli, if I attach to a running asp.net core program and put a breakpoint in a controller method, the debugger does not stop at the breakpoint when the controller endpoint is called.

To reproduce, clone this repo: https://github.com/FabianGosebrink/ASPNETCore-WebAPI-Sample
Try to debug one of the controller methods by placing a breakpoint, maybe add a `Console.WriteLine` to confirm that it is indeed running.  

Some ideas as to where the problem is originating from (perhaps in the code, maybe in my machine :smile: ) would be appreciated, then I can take a look myself.

**Comment by gbalykov** [comment]
Did you build netcoredbg from source or used binaries? Do you run this on windows or linux?

**Comment by lem102** [comment]
Built from source, on debian linux.

**Comment by gbalykov** [comment]
Please share build commands too

**Comment by lem102** [comment]
I was mistaken in the nature of the bug I am experiencing. I will close this issue and open another one.
