### ISSUE TITLE
How to change current thread?

### ISSUE THREAD

**Issue by qgindi** [Samsung/netcoredbg#150]
Using MI protocol, it seems there is no way to change current thread (`m_debugger.SetLastStoppedThreadId`?). The debugger does not implement `-thread-select` command or `--thread` argument. It seems it is possible only if using the VSCode protocol.

For example, when the user clicks the Pause button, the current thread is the last stopped thread, or a random thread if never stopped (often not even the main thread). Then the user may want to step-debug another thread.

**Comment by viewizard** [comment]
Please note, GDB/MI protocol is not human oriented, IDE/plugins provide proper formed commands with `--thread` if need. I am just worry, why you need this command.

**Comment by viewizard** [comment]
I added this to "feature requests" list (as I see we planned same for CLI too), but at this moment we all involved in porting to riscv64 (.NET runtime/debugger), not sure this will be done in near future.
