### ISSUE TITLE
Break if bad breakpoint condition

### ISSUE THREAD

**Issue by qgindi** [Samsung/netcoredbg#153]
Now, if breakpoint condition is invalid or unsupported, the breakpoint is silently ignored, and the end user does not know why.

Tested how it works in other debuggers: VS, VSCode and Rider. All then display an error message and break.

Feature request: break if bad breakpoint condition. And indicate the error in the `*stopped` event data.

**Comment by viewizard** [comment]
Looks like not only debugger but also IDE related feature (IDE/adapter/plugin should also care about this). Will add same behaviour as VSCode C# debugger have (send breakpoint changed event with condition expression error text + send stderr output event with same text + break on breakpoint).

**Comment by viewizard** [comment]
BTW, not sure about Rider, but I was not able to found any related lines in [MIEngine](https://github.com/microsoft/MIEngine), probably VS C# debugger have some integration in VS IDE (same as it have it for EnC, that not implemented in MIEngine).

**Comment by gbalykov** [comment]
This should be fixed in latest release. Feel free to reopen if you see any more related issues.
