### ISSUE TITLE
Location missing if unhandled Exception occurred in async Main 

### ISSUE THREAD

**Issue by itn3000** [Samsung/netcoredbg#166]
# Overview

Cannot get location of unhandled exception occurred in async Main program.

# Environment

* netcoredbg version: 3.0.0-13 (27606c3, Release)
* os: win10 x64
* dotnet-sdk: 8.0.200
* vscode: 1.86.2
* C# extension: 2.18.16

# Steps to reproduce

1. create new console project
2. open project with vscode
3. write following code
4. start vscode debugging session with following pipeTransport setting

## code example

```csharp
using System;
using System.Threading.Tasks;

class Program
{
    static void Abc()
    {
        throw new Exception();
    }
    static async Task Main()
    {
        await Task.Yield();
        Abc();
    }
}
```

## pipeTransport setting

```json
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "c:/Windows/System32/cmd.exe",
                "pipeArgs": ["/c"],
                "debuggerPath": "d:/bin/netcoredbg/netcoredbg.exe"
            }

```

# Expected

program stops and display exception message.

# Actual

program stopped but no message.
callstack information is "Unknown Source"

## Additional Information

edit Main function to sync, it works as expected.

**Comment by gbalykov** [comment]
Thanks for reporting, we'll take a look

**Comment by viewizard** [comment]
Looks like `async` methods should care about exceptions in another way:
```
<- (E) {"body":{"allThreadsStopped":true,"reason":"exception","text":"An unhandled exception of type 'System.Exception' occurred in System.Private.CoreLib.dll","threadId":93289},"event":"stopped","seq":"14","type":"event"}
```
plus, in this case we have some "exception handler" (not user code)
![Screenshot 2024-02-28 235650](https://github.com/Samsung/netcoredbg/assets/15098562/3afc3021-3135-417d-b829-5367000a18b9)
in the same time, if I click on top frame, I see proper exception data:
![Screenshot 2024-02-29 001547](https://github.com/Samsung/netcoredbg/assets/15098562/27e81426-e39b-4f80-ae99-51a2bc628553)


For example, MS C# debugger:
```
<- (E) {"seq":28,"type":"event","event":"stopped","body":{"reason":"exception","threadId":93792,"text":"An exception of type 'System.Exception' occurred in vscode_test.dll but was not handled in user code","allThreadsStopped":true,"source":{"name":"Program.cs","path":"/home/viewizard/Desktop/projects_test/vscode_test/Program.cs"},"line":8,"column":9}}
```
![Screenshot 2024-02-29 001147](https://github.com/Samsung/netcoredbg/assets/15098562/c3915163-f1c6-413f-8a7a-b025b0690878)

**Comment by gbalykov** [comment]
This should be fixed in latest release. Feel free to reopen if you see any more related issues.
