### ISSUE TITLE
Shows warning even though works properly

### ISSUE THREAD

**Issue by MuriMan** [Samsung/netcoredbg#168]
```
ncdb> file check
ncdb> b Program.cs:2
 Breakpoint 1 at Program.cs:2 --pending, warning: No executable code of the debugger's target code type is associated with this line.
ncdb>
```
the warning is unnecessary, how to turn it off?

**Comment by viewizard** [comment]
This is part of breakpoint setup response message, not warning itself. You can't turn it off.

**Comment by MuriMan** [comment]
Is it meant to happen?

**Comment by viewizard** [comment]
Yes, this is normal output for this case (breakpoint setup before debuggee process start).

**Comment by MuriMan** [comment]
understood
