### ISSUE TITLE
path to libdbgshim.so  is hardcoded on ARM/Tizen

### ISSUE THREAD

**Issue by 0xfk0** [Samsung/netcoredbg#17]
The fact, that path is hardcoded prevents installing multiple different versions of netcoredbg on the computer (mobile phone, etc...)  Especially it's impossible to install, for debugging purposes, particular versions of CoreCLR, CoreFX and netcoredbg in separate directory without touching phone's rootfs.

I think, that path to libdbgshim.so shouldn't be hardcoded, but should be determined by LD_LIBRARY_PATH environment variable, as for other libraries (typical behaviour).  And only in case, when libdbgshim.so can't be found in places, where other libraries are searched, only in this case harcoded path should be tried as second option.

**Comment by viewizard** [comment]
We have hardcoded path for Tizen OS during rpm build only. If you build new CoreCLR for testing, with some custom location why not just build custom netcoredbg rmp with custom CoreCLR location too? -https://github.com/Samsung/netcoredbg/blob/db69338cf1606d8d327de0eaaf1694d8463af135/packaging/netcoredbg.spec#L92
Anyway you will need change installation path for different debugger version by change, right? https://github.com/Samsung/netcoredbg/blob/db69338cf1606d8d327de0eaaf1694d8463af135/packaging/netcoredbg.spec#L44

Note, debugger should use same or newer version of `libdbgshim.so` as runtime have. You can't just use some `libdbgshim.so` for any CoreCLR versions. In the same time debugger could work with any `libdbgshim.so`/CoreCLR versions. This is why for Tizen OS `libdbgshim.so` located in the same directory as runtime itself.

This not looks like common usage, we will not implement this for Tizen OS rpm build for sure.
