### ISSUE TITLE
Failing to load symbols with NetCoreDbg and Godot

### ISSUE THREAD

**Issue by SchnozzleCat** [Samsung/netcoredbg#173]
I am trying to attach to a running Godot session with netcoredbg and Neovim. Netcoredbg definitely works with Godot, since VSCode has no issues attaching to a running godot session.

The issue I am running into is that the debugger attaches just fine, but it fails to load the symbols for my Godot project. The DAP log shows the following for my rejected breakpoint:

```
[ INFO ] 2024-08-01T19:50:33Z+0200 ] ...pack/myNeovimPackages/start/nvim-dap/lua/dap/session.lua:904 ]    "Breakpoint unverified"    {
  id = 2,
  line = 16,
  message = "The breakpoint will not currently be hit. No symbols have been loaded for this document.",
  verified = false
}
```

Running netcoredbg in CLI mode shows the following:

```
...

library loaded: /nix/store/bq5bzv8d9dq1jsz40dsfxjsnns8bhaav-godot4-mono-schnozzlecat-4.3.0-rc1/bin/GodotSharp/Api/Debug/GodotPlugins.dll
symbols loaded, base address: 0x7f8aac00f000, size: 12800(0x3200)

...

library loaded: /nix/store/bq5bzv8d9dq1jsz40dsfxjsnns8bhaav-godot4-mono-schnozzlecat-4.3.0-rc1/bin/GodotSharp/Api/Debug/GodotSharp.dll
symbols loaded, base address: 0x7f8a60400000, size: 5344256(0x518c00)

...

library loaded: TestNetCoreDbg
no symbols loaded, base address: 0x7f8aac002000, size: 7168(0x1c00)
```

Where ``TestNetCoreDbg`` is the DLL for my project. It seems to load the DLLs for the Godot<->C# glue code just fine, but for some reason it does not find (?) the PDB for the runtime code specific to the loaded project, even though it is right beside the DLL. Even running the debugger from this folder doesn't seem to do the trick.

![image](https://github.com/user-attachments/assets/5c43a1c3-f2fa-435c-a9ae-b0acebe04d30)

I've also specified full debug symbols, but that also doesn't seem to help.

```
<Project Sdk="Godot.NET.Sdk/4.3.0-SchnozzleCat-e83503f.808">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <DebugType>full</DebugType>
  </PropertyGroup>
</Project>

```

What am I missing here? I've been trying to get this to work for some time now with no avail... Any help is greatly appreciated!

**Comment by viewizard** [comment]
`bq5bzv8d9dq1jsz40dsfxjsnns8bhaav-godot4-mono-schnozzlecat-4.3.0-rc11` looks like `mono` build, not sure netcoredbg aimed to `coreclr` only will work proper at all.

**Comment by SchnozzleCat** [comment]
> `bq5bzv8d9dq1jsz40dsfxjsnns8bhaav-godot4-mono-schnozzlecat-4.3.0-rc11` looks like `mono` build, not sure netcoredbg aimed to `coreclr` only will work proper at all.

This is just historical naming on my part (the package used to be called [godot3-mono](https://mynixos.com/nixpkgs/package/godot3-mono)), the name is up to me as this is built from source.

Since Godot 4.0 [it now uses CoreCLR](https://godotengine.org/article/whats-new-in-csharp-for-godot-4-0/#runtime-changes).

Rider also lists the project as using net8.0.

**Comment by gbalykov** [comment]
@SchnozzleCat is your TestNetCoreDbg.dll built in debug or release? For release you'll need https://github.com/Samsung/netcoredbg/blob/master/docs/cli.md#debugging-release-build-of-dlls. 

Also please share version of NetCoreDbg that you use and build command & commit if you built it from source code.

**Comment by SchnozzleCat** [comment]
> @SchnozzleCat is your TestNetCoreDbg.dll built in debug or release? For release you'll need https://github.com/Samsung/netcoredbg/blob/master/docs/cli.md#debugging-release-build-of-dlls.
> 
> Also please share version of NetCoreDbg that you use and build command & commit if you built it from source code.

It should use debug by default but I just tested again with explicitly specifying the configuration and it still fails to load the symbols.

```
dotnet build --configuration DEBUG
  Determining projects to restore...
  Restored /home/linus/Repositories/testnetcoredbg/TestNetCoreDbg.csproj (in 109 ms).
/home/linus/Repositories/testnetcoredbg/ScriptToDebug.cs(8,9): warning CS0219: The variable 'i' is assigned but its value is never used [/home/linus/Repositories/testnetcoredbg/TestNetCor
eDbg.csproj]
  TestNetCoreDbg -> /home/linus/Repositories/testnetcoredbg/.godot/mono/temp/bin/Debug/TestNetCoreDbg.dll

Build succeeded.

/home/linus/Repositories/testnetcoredbg/ScriptToDebug.cs(8,9): warning CS0219: The variable 'i' is assigned but its value is never used [/home/linus/Repositories/testnetcoredbg/TestNetCor
eDbg.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.62
``` 

The package comes from my package manager, but that [builds from source and caches the binaries](https://github.com/NixOS/nixpkgs/blob/e2dd4e18cc1c7314e24154331bae07df76eb582f/pkgs/development/tools/misc/netcoredbg/default.nix#L85).
This is my version output:
```
❯ netcoredbg --version
NET Core debugger 3.0.0-13 (not detected, Release)

Copyright (c) 2020 Samsung Electronics Co., LTD
Distributed under the MIT License.
See the LICENSE file in the project root for more information.
```

There's a [pull request open for Nix](https://github.com/NixOS/nixpkgs/pull/329845) that upgrades to ``3.1.0-1031``, so I'm going to test that next.

**Comment by SchnozzleCat** [comment]
After upgrading to ``3.1.0-1031``, everything works perfectly :upside_down_face: . Sorry for wasting your time, and thanks for the help!
