### ISSUE TITLE
Is it possible to use this debugger with VS Code?

### ISSUE THREAD

**Issue by NatElkins** [Samsung/netcoredbg#179]
I see it supports the VS Code protocol, but I don't see any documentation on how to actually use it from VS Code, just the CLI.  Is this something that is supported?

Thank you!

**Comment by NatElkins** [comment]
I see this comment by @dkattan, so I think it must be possible.  That's my exact use case, to use the debugger with Cursor.

https://github.com/Samsung/netcoredbg/pull/176#issuecomment-2393252832

**Comment by veghivan** [comment]
Yup let me show you how I got it working,
launch.json:
>         {
>             "name": ".NET Core Launch (netcorDbg)",
>             "type": "coreclr",
>             "request": "launch",
>             "program": "${workspaceFolder}/Gy_08_OBS_SINGL/bin/Debug/net8.0/Gy_08_OBS_SINGL.dll",
>             "args": [],
>             "cwd": "${workspaceFolder}",
>             "console": "integratedTerminal",
>             "stopAtEntry": false,
>             "externalConsole": false,
>             "pipeTransport": {
>                 "pipeCwd": "${workspaceFolder}",
>                 "pipeProgram": "bash",
>                 "pipeArgs": ["-c"],
>                 "debuggerPath": "/usr/bin/netcoredbg", //your install of netcoredbg
>                 "quoteArgs": true
>             }
>         },

**Comment by NatElkins** [comment]
@veghivan What architecture are you on?  I'm on an M3 Mac.

**Comment by veghivan** [comment]
> @veghivan What architecture are you on? I'm on an M3 Mac.

An old lenovo t470s running Arch meaning x86_64.

**Comment by NatElkins** [comment]
Thanks, I'll close this anyway as it's clearly possible, I just need to get my hands on the right binary.
