### ISSUE TITLE
Netcoredbg can't be compiled with CoreCLR 3.0

### ISSUE THREAD

**Issue by 0xfk0** [Samsung/netcoredbg#18]
Currently Netcoredbg (from master branch) can't be compiled with CoreCLR 3.0 on Linux.
Steps to reproduce the issue are following (microsoft's dotnet should be installed in /usr/share):

1) checkout microsoft's CoreCLR from https://github.com/dotnet/coreclr.git, tag v3.0.0-preview4-27612-72 or similar;
2) build CoreCLR with the following command: `./build.sh -debug -verbose -clang6.0`;
3) checkout Netcoredbg to separate directory from `https://github.com/dotnet/coreclr.git`, master branch;
4) change directory to place where Netcoredbg sources reside, make `build` director, change directory to `build`;
5) in `build` directory run following command to configure Netcoredbg:
`CC=clang-6.0 CXX=clang++-6.0 cmake .. -DCMAKE_INSTALL_PREFIX=/some/path -DCORECLR_DIR=/home/sysop/coreclr.microsoft -DDOTNET_DIR=/usr/share/dotnet -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`
6) run `make`.

Compilation fails with messages showing, that some types or symbols are not defined. 

The issues exists because of absence right #include directives in Netcoredbg's code. Previously required files was included by accident, because some vital include-files included via "assert.h" file, but now system-wide (but not microsoft's one) file is used.

**Comment by viewizard** [comment]
Was fixed for 3.0 release.
