### ISSUE TITLE
The "process" event is not raised

### ISSUE THREAD

**Issue by lextm** [Samsung/netcoredbg#20]
vsdbg raises a "process" event when it launches a new process,
```
{
    "seq":6,
    "type":"event",
    "event":"process",
    "body":
    {
        "name":"/Users/lextm/consoletest/bin/Debug/netcoreapp2.1/consoletest.dll",
        "systemProcessId":81517,
        "isLocalProcess":true,
        "startMethod":"launch"
    }
}
```
which allows the editor/IDE talks to vsdbg learning the process information and perform other initialization (such as setting break points).

However, this project does not raise the same event.

Can this be added?

**Comment by lextm** [comment]
Related to #11

**Comment by lextm** [comment]
The process event is documented in the protocol

https://microsoft.github.io/debug-adapter-protocol/specification

I proposed a simple implementation for review.

**Comment by viewizard** [comment]
Looks like this functionality was added in 645d19d
