### ISSUE TITLE
Breakpoints do not break for generated code

### ISSUE THREAD

**Issue by lordmampf** [Samsung/netcoredbg#27]
Hello,

Thank you for this great debugger. It's working for me with compiled code in vs.
But when I generate an assembly with roslyn a breakpoint does not break.

I created a small sample project:

https://github.com/lordmampf/PlaygroundForSamsungNetcoredbg
To test start both projects without the vs debugger.
When using roslyn a breakpoint does not work.

Do you have any ideas how to fix this issue?
Is this an issue with the debugger?

Thank you!

**Comment by ayuckhulk** [comment]
Hello! Thank you for the kind words!
In order for breakpoints to work you need a PDB file with debug info alongside your DLL.

I guess you need to add some `EmitOptions` with `DebugInformationFormat.PortablePdb` (see https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.emit.debuginformationformat?view=roslyn-dotnet)

Maybe a thread on StackOverflow could help you: https://stackoverflow.com/questions/50649795/how-to-debug-dll-generated-from-roslyn-compilation

**Comment by lordmampf** [comment]
Hello ;)

Yes sure, I forgot that in this example.
Now I use the code from stackoverflow to generate the assembly.

I'm getting an breakpoint changed event with verified = true, but the breakpoint still does not break.

**Comment by lextm** [comment]
It will not break, because of #20 and #19 .

**Comment by lordmampf** [comment]
Hello,

Thank you very much for your help!
It's working now.

My mistake was, that I had to remove the compiled code from the project.
Because the sourefile was used in two different assemblies.

@lextm I tested https://github.com/lextm/netcoredbg/commit/0fcaf6877d3085b18049d2bdeca69685db561b94 on your test branch. For me it's working with this version and your version as well.
