### ISSUE TITLE
Ship ready-to-use binary

### ISSUE THREAD

**Issue by mickaelistria** [Samsung/netcoredbg#3]
To simplify adoption, it would be nice if netcoredbg could ship pre-built and ready-to-use tarballs or zips containing the binary.

**Comment by ayuckhulk** [comment]
@mickaelistria Thanks for the suggestion! I'm plannning to introduce nightly builds soon.

**Comment by ayuckhulk** [comment]
@mickaelistria I added automatic builds from master branch, you can grab binaries from https://github.com/Samsung/netcoredbg/releases/tag/latest

**Comment by mickaelistria** [comment]
I could try it and get the dotnet debugger working over the Debug Adapter Protocol in Eclipse IDE !
Awesome!
