### ISSUE TITLE
No binary generated compiling in MacOS Mojave

### ISSUE THREAD

**Issue by ClimberBear** [Samsung/netcoredbg#30]
I have just tried to compile in MacOS, and it doesn't report any error, but doesn't create the bin folder.

I attach the output of cmake.

Versions: MacOS Mojave 10.14.6
XCode 10.3
cc -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[cmake_output.txt](https://github.com/Samsung/netcoredbg/files/3500899/cmake_output.txt)

**Comment by viewizard** [comment]
Hello,
could you please provide log for second command (```cmake --build . --target install```), where you actually should build debugger binary.

**Comment by ClimberBear** [comment]
Thanks!

Now have generated the bin folder and binary. Maybe my past tries were not correct.

P.S: But still now work. I will open another issue
