### ISSUE TITLE
Package for conda-forge

### ISSUE THREAD

**Issue by saraedum** [Samsung/netcoredbg#31]
I'd like to package this for conda-forge. Is there any chance you could create a release/tag that we could then distribute?

**Comment by saraedum** [comment]
So, to reiterate. Not having tagged releases makes it very hard for distributions to include package this. To some extent distributions are very reluctant to include code that is so alpha that it does not even have a version number.

**Comment by viewizard** [comment]
CI/CD now automatically add version and tag for releases. Hope, this helps in your work.
