### ISSUE TITLE
Trying to use MI via Emacs, I get notes about unsupported commands?

### ISSUE THREAD

**Issue by sebasmonia** [Samsung/netcoredbg#33]
This might be a problem with the module calling the debugger rather than `netcoredbg`, when running the debugger I get the following errors:

`netcoredbg --interpreter=mi --attach 68528` where 68528 is the PID of my test app.

```
(gdb)
1^done
(gdb)
2^done
(gdb)
3^done
(gdb)
4^error,msg="Unknown command: enable-pretty-printing"
(gdb)
5^error,msg="Unknown command: file-list-exec-source-files"
(gdb)
6^error,msg="Unknown command: file-list-exec-source-file"
(gdb)
7^error,msg="Error: 0x80004005"
(gdb)
8^error,msg="Unknown command: stack-info-frame"
(gdb)
9^done,threads=[{id="85316",name="<No name>",state="running"},{id="84512",name="<No name>",state="running"}]
(gdb)
10^error,msg="Unknown command: break-list"
(gdb)
11^done,threads=[{id="85316",name="<No name>",state="running"},{id="84512",name="<No name>",state="running"}]
(gdb)
12^error,msg="Unknown command: break-list" 
(gdb)
```
Are these unsupported MI commands?
I'm also reaching to the debugging tool authors.

Thank you!

**Comment by alpencolt** [comment]
@sebasmonia NetcoreDbg is designed to work mainly with Visual Studio and VS Code and supports command which used by these IDEs.
`enable-pretty-printing`, `file-list-exec-source-files`, `file-list-exec-source-file`, `stack-info-frame`, `break-list` are not supported.

**Comment by sebasmonia** [comment]
Thank you for quick turnaround. Is there any plans to support the full MI command set?

Regardless of the answer, I'm closing this issue, as the debugger is working as intended.

**Comment by alpencolt** [comment]
Currently don't have, but we're open for PRs.
