### ISSUE TITLE
Any plans to compile for Raspberry Pi?

### ISSUE THREAD

**Issue by nrushforth** [Samsung/netcoredbg#36]
Is there anyway that this could be compiled to work with the Raspberry Pi architecture?

**Comment by a-zh** [comment]
@nrushforth Can you show any errors from the building log?
So fa, we have't plans to support Raspberry PI, right now.

**Comment by nrushforth** [comment]
@a-zh I haven't tried compiling the source on a PI. I was curious as this would get round the problem of the provided debugger with vscode not working on the PI.

**Comment by viewizard** [comment]
I was able to build and tested it on rpi4 with Ubuntu 18.04 64bit image (https://ubuntu.com/download/raspberry-pi).
You will need .Net SDK 3.1 for Linux ARM64 (https://dotnet.microsoft.com/download/dotnet-core/3.1) and CoreCLR 3.1 sources (https://github.com/dotnet/coreclr/tree/release/3.1) in order to build it:
```
mkdir build
cd build
CC=clang CXX=clang++ cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../bin -DCORECLR_DIR=./coreclr -DDOTNET_DIR=./sdk
cmake --build . --target install
```

**Comment by nrushforth** [comment]
Any way you can share the compiled code?

**Comment by viewizard** [comment]
Unfortunately I didn't stored binaries and now don't have rpi4 with Ubuntu to rebuild them.

**Comment by Cyber1000** [comment]
This thread is a little bit old, but I've managed to cross-compile for arm64 (works on my rpi4 with raspberry OS 64 bit), for anything interested, let me know if it works: https://github.com/Cyber1000/netcoredbg/releases/tag/1.2.0-825.arm64.alpha

**Comment by Cyber1000** [comment]
@a-zh just a mention, since I don't know if anyone is actively listening.

**Comment by viewizard** [comment]
Should build without any issues now. Plus, we provide now RPI arm64 build (netcoredbg-linux-arm64.tar.gz), see [release ](https://github.com/Samsung/netcoredbg/releases) page.
