### ISSUE TITLE
Build on Raspberry PI fails at Linking

### ISSUE THREAD

**Issue by nrushforth** [Samsung/netcoredbg#37]
I get this error when trying to build on Raspberry PI.

Any ideas?

[ 39%] Built target corguids
[ 42%] Linking CXX executable netcoredbg
CMakeFiles/netcoredbg.dir/manageddebugger.cpp.o: In function `ManagedCallback::QueryInterface(_GUID const&, void**)':
/home/pi/.vs/netcoredbg-master/9103d73c-20b3-4998-995b-f066353b263b/src/src/debug/netcoredbg/manageddebugger.cpp:312: undefined reference to `IID_IUnknown'
/home/pi/.vs/netcoredbg-master/9103d73c-20b3-4998-995b-f066353b263b/src/src/debug/netcoredbg/manageddebugger.cpp:312: undefined reference to `IID_IUnknown'
collect2: error: ld returned 1 exit status
src/debug/netcoredbg/CMakeFiles/netcoredbg.dir/build.make:339: recipe for target 'src/debug/netcoredbg/netcoredbg' failed
make[2]: *** [src/debug/netcoredbg/netcoredbg] Error 1
CMakeFiles/Makefile2:124: recipe for target 'src/debug/netcoredbg/CMakeFiles/netcoredbg.dir/all' failed
Makefile:129: recipe for target 'all' failed
make[1]: *** [src/debug/netcoredbg/CMakeFiles/netcoredbg.dir/all] Error 2
make: *** [all] Error 2

**Comment by a-zh** [comment]
@nrushforth It's looks as a linkage issue.

1) Which version of RP do you use?
2) Please show me all your build command steps include `git clone`.

**Comment by nrushforth** [comment]
@a-zh Thanks for getting back to me.

1. I am using a RPI 3B
2. I have not created a git clone of the code I have downloaded it locally to my Macbook, and I am using Windows 10 in a VM to Build this via Visual Studio 2019, that SSH remotes to my PI to do the actual build (it uses the Linux Cross compilation add-in to Visual Studio). I can zip up the code from the PI which contains all the cmake output.

**Comment by a-zh** [comment]
OK, let's try to look at the full log. Thank you.

Unfortunately, I don't have `RP3` in hand right now.
I need a more time for reproducing. But, so, 
How about to build `NetcoreDBG` on `RP3` via `SSH` from `terminal`?
Please, tell me, what scenario of using debugger do you need?

**Comment by nrushforth** [comment]
I am new to CMake as I am used to using Visual Studio to build C# apps. 

Any idea of the command line to build on the terminal. 

Use case for debugger is that the omnisharp one does not work on raspberry pi. it does not support armv7l. So hoping that building this allows debugging of .net core code in vscode on raspberry pi.

**Comment by saraedum** [comment]
I believe that #31 might resolve this for you. I could package this for conda-forge which might make this work for RaspberryPi (have not checked whether all the dependencies are available.)

**Comment by nrushforth** [comment]
> I believe that #31 might resolve this for you. I could package this for conda-forge which might make this work for RaspberryPi (have not checked whether all the dependencies are available.)

Happy to give this a try if you have a package available.

**Comment by saraedum** [comment]
Sure. I'll let you know. Just waiting for the repo owners to tag a release.

**Comment by viewizard** [comment]
Should build without any issues now. Plus, we provide now RPI arm64 build (netcoredbg-linux-arm64.tar.gz), see [release ](https://github.com/Samsung/netcoredbg/releases) page.
