### ISSUE TITLE
Problem with debugging simple .Net mvc application

### ISSUE THREAD

**Issue by svor** [Samsung/netcoredbg#39]
I'm trying to debug simple .Net mvc application which was generated by the command:
`dotnet new mvc --no-https --auth None`

When I run debug configuration in VS Code, it starts running the application and stops at entry but it freezes at 
```c#
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
        }
```
As a result the application doesn't start fully and the debugger is frozen. Any idea what is wrong?

**Netcoredbg Log file** 
https://gist.github.com/svor/13af827c7d00b2577aeb7038a70a6412

**VS Code debug configuration**
```json
{
    "version": "0.2.0",
    "configurations": [
    
        {
             "name": ".NET Core Launch (console)",
             "type": "coreclr",
             "request": "launch",
             "program": "/home/vsvydenko/tmp/net-core-mvc/bin/Debug/netcoreapp3.0/net-core-mvc.dll",
             "args": [],
             "cwd": "${workspaceFolder}",
             "console": "internalConsole",
             "stopAtEntry": true,
             "internalConsoleOptions": "openOnSessionStart",
 
             "pipeTransport": {
                 "pipeCwd": "${workspaceFolder}",
                 "pipeProgram": "bash",
                 "pipeArgs": ["-c"],
                 "debuggerPath": "/home/vsvydenko/bin/netcoredbg/netcoredbg  --engineLogging=/tmp/a",
                 "quoteArgs": true
             }
         },
     ]
 }
```

**Short video** 
https://youtu.be/beBx9X_bh6g

**Environment**
os: Linux Mint 19.3 (x86-64)
dotnetcore-sdk: 3.0.1
netcoredbg: latest releas

**Comment by a-zh** [comment]
@svor Thanks a lot. I cannot reproduce the issue. I checked on Ubuntu 18.04. And I didn't see any problems. In video I saw the pause of debugger, but debugger wait of process (browser) running.
Can you check syslog?

1) Please, add to launch.json this options and give me the log:
``` 
        "logging": {
                "engineLogging": true
            },
```
Should be in launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
    
        {
             "name": ".NET Core Launch (console)",
             "type": "coreclr",
             "request": "launch",
             "program": "/home/vsvydenko/tmp/net-core-mvc/bin/Debug/netcoreapp3.0/net-core-mvc.dll",
             "args": [],
             "cwd": "${workspaceFolder}",
             "console": "internalConsole",
             "stopAtEntry": true,
             "internalConsoleOptions": "openOnSessionStart",
             "logging": {
                 "engineLogging": true
             },
             "pipeTransport": {
                 "pipeCwd": "${workspaceFolder}",
                 "pipeProgram": "bash",
                 "pipeArgs": ["-c"],
                 "debuggerPath": "/home/vsvydenko/bin/netcoredbg/netcoredbg  --engineLogging=/tmp/a",
                 "quoteArgs": true
             }
         },
     ]
 }
```
2) Also, please check with netcoreapp2.2 instead netcoreapp3.0


3) And, please check without `"pipeTransport"`:
Should be in launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
    
        {
             "name": ".NET Core Launch (console)",
             "type": "coreclr",
             "request": "launch",
             "program": "/home/vsvydenko/tmp/net-core-mvc/bin/Debug/netcoreapp3.0/net-core-mvc.dll",
             "args": [],
             "cwd": "${workspaceFolder}",
             "console": "internalConsole",
             "stopAtEntry": true,
             "internalConsoleOptions": "openOnSessionStart",
             "logging": {
                 "engineLogging": true
             }
         },
     ]
 }
```

**Comment by joern-h** [comment]
Hi, i have the exact same issue with my mvc angular app:

Log: https://paste.linux.pizza/?e11e540467739a4f#9yp7wM8d7BaWKHNJAvyuZzrNawWx7vGmMxRZia9rApfS

lauch.json

```
{
    "name": ".NET Core Launch (web) [netcoredbg]",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/MusicManager.dll",
    "args": [],
    "cwd": "${workspaceFolder}",
    "stopAtEntry": false,
    "logging": {
        "engineLogging": true
    },
    "serverReadyAction": {
        "action": "openExternally",
        "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"
    },
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    },
    "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
    },
    "pipeTransport": {
        "pipeCwd": "${workspaceFolder}",
        "pipeProgram": "bash",
        "pipeArgs": ["-c"],
        "debuggerPath": "/usr/bin/netcoredbg --engineLogging=/tmp/a",
        "quoteArgs": true
    }
}

```

Log without `"pipeTransport":`
https://paste.linux.pizza/?bad818c7fa0d9d88#4cTgpoNkqEmR6a6cdYCQLwqps4RUNWNkg9DviDJehkJ8

**Comment by svor** [comment]
Hello @a-zh, thank you for the answer.
 It doesn't look like the debugger waits of browser running, i tried to open browser - the result was the same.

The file with logs was attached in the description, here it is:
https://gist.github.com/svor/13af827c7d00b2577aeb7038a70a6412

I cannot skip `pipeTransport` because there is only way I know to use netcoredbg in VS Code

**Comment by a-zh** [comment]
For this case:
> 
> The file with logs was attached in the description, here it is:
> https://gist.github.com/svor/13af827c7d00b2577aeb7038a70a6412
> 

1) Does vsdbg debugger freezes too or not?
2) Does the WEB browser work or not?

**Comment by a-zh** [comment]
@svor @joern-h Please, try this project with `netcoreapp2.2` and `netcoredbg`.

[project.tar.gz](https://github.com/Samsung/netcoredbg/files/4408227/project.tar.gz)

**Comment by joern-h** [comment]
@a-zh 
I tried with your project with `netcoreapp2.2` and `netcoredbg` and the same problem and the debugger freezes again.

It does not freeze with `vsdbg` and the browser opens.

But with `netcoredbg` it freezes and no browser opens...

Log: https://paste.linux.pizza/?f657698128316c64#BD2onk17hNVyeLs8BcitjzUCaG2haxsBdJ6738vkUFTu

It freezes after: `services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`
Startup.cs line 34

**Comment by svor** [comment]
@a-zh @joern-h 
the same result is on my side: `netcoredbg` freezes and the browser doesn't open

```
dotnet --version
2.2.402
```

Log file is here: https://gist.github.com/svor/a5a78db4e61cd779a97d1d59e013a880

**Comment by a-zh** [comment]
@joern-h @svor 

I **reproduced** it once. 
Netcoredbg has a problem with starting process at the first run.
I will investigate it.

But now, you can check `netcoredbg` with second and following runs.  
Please, kill all of the dotnet and netcoredbg process:
```
ps auxww|grep dotnet
ps auxww|grep netcoredbg
kill -9 <pids>
```
Please, clean and rebuild the project.
Run debug, press F5 a few time before freezing and press Stop button.
Run debug again and tell me please result about running web browser.

**Comment by svor** [comment]
@a-zh 
The way which you described works. By pressing a few times F5 (which means continue in debug mode) the page opens in the browser.

**Comment by joern-h** [comment]
Sadly, pressing F5 a few times does not work on my angular app...

The server starts, but something is still wrong:
https://paste.linux.pizza/?95d95581799089ea#BnMxNa3Sj1tLyAxVVsnodSKiDRhwHmq3qhwzNMzXffDp

**Comment by a-zh** [comment]
@joern-h

> Sadly, pressing F5 a few times does not work on my angular app...
> 
@svor I found the issue with threads command. Fixes on review. And I see, that the webserver starts and webpage available from web-browser. Auto starting of webbrowser not supported right now.

> The server starts, but something is still wrong:
> https://paste.linux.pizza/?95d95581799089ea#BnMxNa3Sj1tLyAxVVsnodSKiDRhwHmq3qhwzNMzXffDp

Its looks like another issue. Please, give me more info of your project. I need full project sources for reproduce issue or `dotnet` command for generation the same project.

**Comment by joern-h** [comment]
@a-zh you can reproduce it by creating a new dotnet angular project:

`dotnet new angular -o angular`

and here is the `launch.json`

https://paste.linux.pizza/?13c14126dc33921d#6iAttBdu1kHAq9qyhYsugqavyd4KExqs7XWJh5yVweyE

dotnet --version 3.1.201

**Comment by viewizard** [comment]
@joern-h @svor netcoredbg sources was updated with changes, that should fix this issue. Could you please check it?

**Comment by ppa93** [comment]
@viewizard 
Unfortunately, netcoredbg is still frozen, when try to debug MVC app.

**Comment by mitoriko** [comment]
I found use AddMvcCore() instead of AddMvc() ,netcoredbg will run well, but I don't know why...

**Comment by viewizard** [comment]
I tested with application created by `dotnet new mvc --no-https --auth None` with .NET SDK 3.1, don't see any issues with current debugger release. Please reopen in case you still have this issue.
![Screenshot 2023-04-21 220911](https://user-images.githubusercontent.com/15098562/233716183-9506169c-cd50-4d56-a842-7479ceab33aa.png)
