### ISSUE TITLE
netcoredbg just exits after Launch request

### ISSUE THREAD

**Issue by puremourning** [Samsung/netcoredbg#48]
Hi, 
I just upgraded the version of netcoredbg in [vimspector](https://github.com/puremourning/vimspector) and now with the [test application here](https://github.com/puremourning/vimspector/tree/master/support/test/csharp), netcoredbg just exits after vimspector sends the launch request. Here's the message trace:

```
2020-11-07 18:23:47,463 - INFO - Starting debug adapter with: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/Users/ben/.vim/vimspector-conf/gadgets/macos/netcoredbg/netcoredbg", "--interpreter=vscode"], "name": "netcoredbg"}
2020-11-07 18:23:47,469 - INFO - Debug Adapter Started
2020-11-07 18:23:47,470 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "netcoredbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2020-11-07 18:23:47,474 - DEBUG - Message received: {'seq': 1, 'body': {'capabilities': {'supportTerminateDebuggee': True, 'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsExceptionInfoRequest': True, 'supportsFunctionBreakpoints': True}}, 'event': 'capabilities', 'type': 'event'}
2020-11-07 18:23:47,475 - DEBUG - Message received: {'seq': 2, 'body': {}, 'event': 'initialized', 'type': 'event'}
2020-11-07 18:23:47,475 - DEBUG - Sending Message: {"command": "setBreakpoints", "arguments": {"source": {"name": "Program.cs", "path": "/Users/ben/.vim/bundle/vimspector/support/test/csharp/Program.cs"}, "breakpoints": [{"line": 9}]}, "sourceModified": false, "seq": 1, "type": "request"}
2020-11-07 18:23:47,475 - DEBUG - Sending Message: {"command": "setExceptionBreakpoints", "arguments": {"filters": []}, "seq": 2, "type": "request"}
2020-11-07 18:23:47,475 - DEBUG - Message received: {'seq': 3, 'body': {'supportTerminateDebuggee': True, 'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsExceptionInfoRequest': True, 'supportsFunctionBreakpoints': True}, 'command': 'initialize', 'request_seq': 0, 'success': True, 'type': 'response'}
2020-11-07 18:23:47,475 - DEBUG - LAUNCH!
2020-11-07 18:23:47,475 - DEBUG - Sending Message: {"command": "launch", "arguments": {"request": "launch", "program": "/Users/ben/.vim/bundle/vimspector/support/test/csharp/bin/Debug/netcoreapp2.2/csharp.dll", "args": [], "stopAtEntry": true, "name": "test"}, "seq": 3, "type": "request"}
2020-11-07 18:23:47,478 - INFO - The server has terminated with status -1

```

As you can see:

* we start with `/Users/ben/.vim/vimspector-conf/gadgets/macos/netcoredbg/netcoredbg --interpreter=vscode`
* Send Initialize: `{"command": "initialize", "arguments": {"adapterID": "netcoredbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}`
* Receive capabilities: `{'seq': 1, 'body': {'capabilities': {'supportTerminateDebuggee': True, 'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsExceptionInfoRequest': True, 'supportsFunctionBreakpoints': True}}, 'event': 'capabilities', 'type': 'event'}`
* Received initialised event: `{'seq': 2, 'body': {}, 'event': 'initialized', 'type': 'event'}`
* Send breakpoints:
    * `{"command": "setBreakpoints", "arguments": {"source": {"name": "Program.cs", "path": "/Users/ben/.vim/bundle/vimspector/support/test/csharp/Program.cs"}, "breakpoints": [{"line": 9}]}, "sourceModified": false, "seq": 1, "type": "request"}`
    * `{"command": "setExceptionBreakpoints", "arguments": {"filters": []}, "seq": 2, "type": "request"}`
* Receive initialise response: `{'seq': 3, 'body': {'supportTerminateDebuggee': True, 'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsExceptionInfoRequest': True, 'supportsFunctionBreakpoints': True}, 'command': 'initialize', 'request_seq': 0, 'success': True, 'type': 'response'}`

All good so far. Then we send the `launch` request:

* `{"command": "launch", "arguments": {"request": "launch", "program": "/Users/ben/.vim/bundle/vimspector/support/test/csharp/bin/Debug/netcoreapp2.2/csharp.dll", "args": [], "stopAtEntry": true, "name": "test"}, "seq": 3, "type": "request"}`

But at this point, the netcoredbg process just exits: `The server has terminated with status -1`.

Do you have any idea what's wrong, or how to debug this?

This tested on macOS with netcoredbg `1.2.0-635` and `dotnet 3.1.402`. Haven't tried other Ones.

Thanks,
Ben

ref https://github.com/puremourning/vimspector/issues/290

**Comment by puremourning** [comment]
I added `--log=file` and through some reading of the code found the log file. It just contains this:

```
20-11-09 21:28:19 INFO Start logging
20-11-09 21:28:19 INFO InterpreterVSCode selected
20-11-09 21:28:19 INFO SetDebugger for InterpreterVSCode
20-11-09 21:28:19 INFO pidDebugee = 0
20-11-09 21:28:19 DEBUG > void VSCodeProtocol::EmitCapabilitiesEvent()
20-11-09 21:28:19 DEBUG < void VSCodeProtocol::EmitCapabilitiesEvent()
20-11-09 21:28:19 DEBUG > virtual HRESULT ManagedDebugger::Initialize()
20-11-09 21:28:19 DEBUG > virtual void VSCodeProtocol::EmitInitializedEvent()
20-11-09 21:28:19 DEBUG < virtual void VSCodeProtocol::EmitInitializedEvent()
20-11-09 21:28:19 DEBUG < virtual HRESULT ManagedDebugger::Initialize()
20-11-09 21:28:19 DEBUG > virtual HRESULT ManagedDebugger::SetBreakpoints(std::string, const std::vector<SourceBreakpoint> &, std::vector<Breakpoint> &)
20-11-09 21:28:19 DEBUG < virtual HRESULT ManagedDebugger::SetBreakpoints(std::string, const std::vector<SourceBreakpoint> &, std::vector<Breakpoint> &)
20-11-09 21:28:19 DEBUG > virtual HRESULT ManagedDebugger::InsertExceptionBreakpoint(const ExceptionBreakMode &, const std::__1::string &, uint32_t &)
20-11-09 21:28:19 DEBUG < virtual HRESULT ManagedDebugger::InsertExceptionBreakpoint(const ExceptionBreakMode &, const std::__1::string &, uint32_t &)
```

**Comment by puremourning** [comment]
And running the messages through manually:

```
ben@BenMBP bin % ./netcoredbg --interpreter=vscode
Content-Length: 340^M
^M
{"command": "initialize", "arguments": {"adapterID": "netcoredbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1"
: true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false,
 "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}'
Content-Length: 254

{"seq":1,"body":{"capabilities":{"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest
":true,"supportsExceptionInfoRequest":true,"supportsFunctionBreakpoints":true}},"event":"capabilities","type":"event"}Content-Length: 56

{"seq":2,"body":{},"event":"initialized","type":"event"}Content-Length: 271

{"seq":3,"body":{"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supports
ExceptionInfoRequest":true,"supportsFunctionBreakpoints":true},"command":"initialize","request_seq":0,"success":true,"type":"response"}C
ontent-Length: 238^M
^M
{"command": "setBreakpoints", "arguments": {"source": {"name": "Program.cs", "path": "/Users/ben/.vim/bundle/vimspector/support/test/csh
arp/Program.cs"}, "breakpoints": [{"line": 9}]}, "sourceModified": false, "seq": 1, "type": "request"}'
Content-Length: 227

{"seq":4,"body":{"breakpoints":[{"id":1,"line":9,"message":"The breakpoint is pending and will be resolved when debugging starts.","veri
fied":false}]},"command":"setBreakpoints","request_seq":1,"success":true,"type":"response"}Content-Length: 97^M
^M
{"command": "setExceptionBreakpoints", "arguments": {"filters": []}, "seq": 2, "type": "request"}'
Content-Length: 136

{"seq":5,"body":{"supportsExceptionOptions":false},"command":"setExceptionBreakpoints","request_seq":2,"success":true,"type":"response"}
Content-Length: 238^M
^M
{"command": "launch", "arguments": {"request": "launch", "program": "/Users/ben/.vim/bundle/vimspector/support/test/csharp/bin/Debug/net
coreapp2.2/csharp.dll", "args": [], "stopAtEntry": true, "name": "test"}, "seq": 3, "type": "request"}'
zsh: abort      ./netcoredbg --interpreter=vscode
ben@BenMBP bin % 
```

**Comment by puremourning** [comment]
It's crashing because `cwd` is apparently mandatory now.


<img width="1318" alt="Screenshot 2020-11-09 at 21 53 12" src="https://user-images.githubusercontent.com/10584846/98600762-fa70b180-22d5-11eb-91ae-3a953701eeee.png">

**Comment by viewizard** [comment]
@puremourning as I know, that was added in order to support VSCode IDE current C# plugin vscode protocol implementation, that explicitly provide `cwd` now. I believe, you could provide `"cwd":""` in order to make it work with netcoredbg.
Something like we have in our tests:
```
{"arguments":{"name":".NET Core Launch (console) with pipeline","type":"coreclr","preLaunchTask":"build","program":"VSCodeExampleTest/bin/Debug/netcoreapp3.1/VSCodeExampleTest.dll","cwd":"","console":"internalConsole","stopAtEntry":true,"internalConsoleOptions":"openOnSessionStart","__sessionId":"25f04dfb-ddd9-4a7c-a6c0-c5417ef86f23"},"command":"launch","seq":2,"type":"request"}
```
I am not sure, why this one was added as required part of `launch` command.

**Comment by puremourning** [comment]
I worked out that adding a cwd makes it stop crashing. 

Are the launch arguments documented anywhere? How will users know what is mandatory? Will netcoredbg frequently introduce breaking changes like this on version change? Perhaps rejecting the message would be better than crashing.

**Comment by viewizard** [comment]
> Are the launch arguments documented anywhere?

All our vscode protocol implementation aimed to cover VSCode C# plugin interaction with debugger. Not sure, that you could find any info except VSCode C# plugin source code.

> How will users know what is mandatory?

We don't provide any docs about vscode protocol, so, source code analyze is the only way for now.

> Will netcoredbg frequently introduce breaking changes like this on version change? 

I hope, no.

> Perhaps rejecting the message would be better than crashing.

Yes, should be fixed. Imo, debugger should return reply with error on such request. I need investigate this code first, I see some lines that worry me now.

**Comment by viewizard** [comment]
I updated git repo:
- "cwd" moved to optional parameters now.
- debugger will care about json code exceptions (this should prevent all related crashes in future + will provide related output).
