### ISSUE TITLE
sending "next" on async/await function returns early

### ISSUE THREAD

**Issue by aqez** [Samsung/netcoredbg#49]
> Additional info can be found at puremourning/vimspector#293

Using this minimal program:
```csharp
using System;
using System.Threading.Tasks;

namespace test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            await DoSomeStuff();
        }

        public static async Task DoSomeStuff()
        {
            Console.WriteLine("Before");
            await Task.Delay(500);
            Console.WriteLine("After");
        }
    }
}
```

When sending the "next" request to step over the line `await Task.Delay(500)`, the next stack trace response then points to the ending curly brace of the `Program.DoSomeStuff` function instead of the line `Console.WriteLine("After")`

Here is what it looks like graphically:
![image](https://user-images.githubusercontent.com/8353400/99132292-517acd00-25db-11eb-92b9-76be1f6bac4a.png)
***Sending "next" request***
```json
{"command": "next", "arguments": {"threadId": 119152}, "seq": 15, "type": "request"}
```
![image](https://user-images.githubusercontent.com/8353400/99132341-70795f00-25db-11eb-97e2-87bead5d5ebc.png)
The next stack trace response now points the current line at the closing brace instead of the line after the awaited function:
```json
{
    "body": {
        "stackFrames": [
            {
                "column": 9,
                "endColumn": 10,
                "endLine": 20,
                "id": 511753943252992,
                "line": 20,
                "moduleId": "963384f9-3e81-445e-9ecf-224b6b1946c5",
                "name": "test.Program.<DoSomeStuff>d__1.MoveNext()",
                "source": {
                    "name": "Program.cs",
                    "path": "/home/aqez/testyo/Program.cs"
                }
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252993,
                "line": 0,
                "moduleId": "00e4cc82-435b-478c-b083-227a479f9d7b",
                "name": "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<System.__Canon>()"
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252994,
                "line": 0,
                "moduleId": "00e4cc82-435b-478c-b083-227a479f9d7b",
                "name": "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<test.Program.<DoSomeStuff>d__1>()"
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252995,
                "line": 0,
                "moduleId": "963384f9-3e81-445e-9ecf-224b6b1946c5",
                "name": "test.Program.DoSomeStuff()"
            },
            {
                "column": 13,
                "endColumn": 33,
                "endLine": 11,
                "id": 511753943252996,
                "line": 11,
                "moduleId": "963384f9-3e81-445e-9ecf-224b6b1946c5",
                "name": "test.Program.<Main>d__0.MoveNext()",
                "source": {
                    "name": "Program.cs",
                    "path": "/home/aqez/testyo/Program.cs"
                }
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252997,
                "line": 0,
                "moduleId": "00e4cc82-435b-478c-b083-227a479f9d7b",
                "name": "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<System.__Canon>()"
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252998,
                "line": 0,
                "moduleId": "00e4cc82-435b-478c-b083-227a479f9d7b",
                "name": "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<test.Program.<Main>d__0>()"
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943252999,
                "line": 0,
                "moduleId": "963384f9-3e81-445e-9ecf-224b6b1946c5",
                "name": "test.Program.Main()"
            },
            {
                "column": 0,
                "endColumn": 0,
                "endLine": 0,
                "id": 511753943253000,
                "line": 0,
                "moduleId": "963384f9-3e81-445e-9ecf-224b6b1946c5",
                "name": "test.Program.<Main>()"
            }
        ],
        "totalFrames": 9
    },
    "command": "stackTrace",
    "request_seq": 16,
    "seq": 36,
    "success": true,
    "type": "response"
}

```

**Comment by aqez** [comment]
Only been looking at the code for a little bit, but maybe an issue in finding the step range of an awaited method call? Maybe here? https://github.com/Samsung/netcoredbg/blob/7219dc5971926a7971b4d5b3655df336532a51a3/src/debug/netcoredbg/manageddebugger.cpp#L1289-L1295

Could it be giving back the last line of the method because it can't find the right sequence point in this method?
https://github.com/Samsung/netcoredbg/blob/7219dc5971926a7971b4d5b3655df336532a51a3/src/debug/netcoredbg/SymbolReader.cs#L413

**Comment by viewizard** [comment]
@aqez I apologize for delay in responding, we have a lot of work now and I did only fast look at related code (didn't found any thing for now), but I have this issue added into list for investigation.

**Comment by kfrolov** [comment]
Please pay attention, that `DoSomeStuff` function doesn't exists in code as is. It is transformed to finite state automata because of `async` keyword, as described here: https://docs.microsoft.com/en-us/archive/msdn-magazine/2011/october/asynchronous-programming-async-performance-understanding-the-costs-of-async-and-await

I think you see wrong source line due to source code transformation.  I have no idea how debugger should handle this case... In practice `DoSomeStuff` will be transformed to a class and few functions: constructor, `MoveNext()`, and `SetStateMachine()`. All variables become the class members.  In theory,  compiler can map distinct source line of original source to some ranges of generated IL code and write this information in PDB files. And debugger can perform reverse operation, and find which line of original source code corresponds to generated code.  Looks something broken here at debugger side.

**Comment by kfrolov** [comment]
And I think, the root cause of issue have no relation with multithreading.

**Comment by aqez** [comment]
I also agree it looks like it is on debugger side. I added some output logging, to see what was going on under the covers and it appears to be giving back the correct offsets, but still stepping too far using ICorDebugStepper.StepRange(). You can see below the ilStartOffset and ilEndOffset are set correctly but the debugger still stepped too far:
![image](https://user-images.githubusercontent.com/8353400/100376744-a8b66f80-2fd5-11eb-98d4-5b560a257d76.png)

**Comment by aqez** [comment]
Interestingly, if we use ICorDebugStepper::Step instead of ICorDebugStepper::StepRange it works, but hits each hidden line as well.

**Comment by viewizard** [comment]
I was finally switched to this issue, and looks like found the point of issue. `ICorDebugStepper` connected to thread, but at `await` we could switch execution thread, so debugger also should remove old stepper (created on old thread) and create new one for same range but for new thread.

This looks like MS debugger have same idea for async/await support in debugger, here is vscode debugger log:
```
-> (C) {"command":"next","arguments":{"threadId":57577},"type":"request","seq":14}
<- (E) {"seq":46,"type":"event","event":"continued","body":{"threadId":57577,"allThreadsContinued":true}}
<- (R) {"seq":47,"type":"response","request_seq":14,"success":true,"command":"next"}
<- (E) {"seq":48,"type":"event","event":"thread","body":{"reason":"started","threadId":57595}}
<- (E) {"seq":49,"type":"event","event":"stopped","body":{"reason":"step","threadId":57595,"allThreadsStopped":true,"source":{"name":"Program.cs","path":"/media/shares/projects/vscode_test/Program.cs"},"line":21,"column":13}}
```
Stepper was created on thread 57577, but step was stopped for thread 57595. In the same time, thread 57577 not execute code any more (will just jump at caller all the time without real code execution).

Need more time for analyze.

**Comment by aqez** [comment]
I can confirm that it works for me. @puremourning may be interested to update vimspector?
