### ISSUE TITLE
Can't change value of variable 

### ISSUE THREAD

**Issue by akurtakov** [Samsung/netcoredbg#5]
I'm using Eclipse aCute which integrated netcoredbg as a debugger in a simple hello world project with a String variable:
```csharp
using System;

namespace NewDotnetProject
{
    class Program
    {
        static void Main(string[] args)
        {
	    String name = "Alex";
            Console.WriteLine("Hello "+ name);
        }
    }
}
```
Putting breakpoint on Console.WriteLine value of variable name can not be changed. Is netcoredbg supporting it ? AFAIK Eclipse LSP4E project which provides the integration with DAP does.

**Comment by mickaelistria** [comment]
Looking at https://github.com/Samsung/netcoredbg/blob/master/src/debug/netcoredbg/vscodeprotocol.cpp#L254 , I do not see a handler for the `setVariable` command as defined in https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L786 , so it seems like it's a missing feature in netcoredbg.

**Comment by ayuckhulk** [comment]
@akurtakov @mickaelistria Setting a variable is not supported yet. Support for modifying simple values (ints, floats, strings etc.) should be finished by october. Stay tuned!

I updated a list of supported features, see wiki https://github.com/Samsung/netcoredbg/wiki/Features

**Comment by ayuckhulk** [comment]
Hey, setting basic values is now supported! You can now set integers, floats, decimals and strings.
