### ISSUE TITLE
List on https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/

### ISSUE THREAD

**Issue by mickaelistria** [Samsung/netcoredbg#6]
netcoredbg should be added to https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/ . The page contains a link to add one entry.

**Comment by ayuckhulk** [comment]
@mickaelistria Thanks for the suggestion! The list you provided contains only VSCode extensions that implement debug adapter protocol. Netcoredbg currently does not have any VSCode extension, so I think it should not be included.
However, tizen.net extension https://marketplace.visualstudio.com/items?itemName=tizen.vscode-tizen-csharp can be added to the list after we update it with netcoredbg support.

**Comment by ayuckhulk** [comment]
@mickaelistria Okay, that's a fair point :smiley: Thanks!
I created a PR here: https://github.com/Microsoft/debug-adapter-protocol/pull/9

**Comment by ayuckhulk** [comment]
Done!
