### ISSUE TITLE
Stepping wrapped debugger causes stdout/stderr reading error

### ISSUE THREAD

**Issue by Martin-Molinero** [Samsung/netcoredbg#61]
Hi all! appreciate your work with this debugger 🙌 

### When
Launching the debugger through another C# processes and redirecting it's input/output, and trying to `step` I would get:
```
stopped, reason: end stepping range, thread id: 1081, stopped threads: all, frame={
    Main.cs:12  (col: 9 to line: 12 col: 10)
    clr-addr: {module-id {d90e33da-6e69-45f7-a539-d4b98ca3e560}, method-token: 0x06000001 il-offset: 54, native offset: 172}
    WhatEver.Pinocho(), addr: 0x00007f51176726f0
}
^exit
stopped, reason: exited, exit-code: 1
```
- More Logs
```
6893984.915 E/NETCOREDBG(P   7, T   8): ioredirect.cpp: worker(307) > child process stdout/stderr reading error
6893984.915 I/NETCOREDBG(P   7, T   8): ioredirect.cpp: operator(135) > IORedirectHelper::worker: terminated
6893984.929 W/NETCOREDBG(P   7, T  16): waitpid.cpp: waitpid(84) > Process terminated without exiting; can't get exit code. Killed by signal 9. Assuming EXIT_FAILURE.
```
### Reproduce:
- OS Linux, tested using released package `netcoredbg-linux-bionic-amd64_1.2.0-782` (tested older versions too)
- interpreter=cli
- **Launching the debugger through another C# processes and redirecting it's input/output, example follows**. The issue doesn't happen if I don't wrap the debugger with another process for some reason 🤔 
- Net5 debugged program and wrapper program

`dotnet wrapper.dll /binaries/for/netcoredbg "--interpreter=cli -ex "run" -- /usr/bin/dotnet /program/to/debug.dll"`

Wrapper program:
``` cs
static void Main(string[] args)
{
    var netcoredbg = args[0];
    var arguments = args[1];

    var process = new Process
    {
        StartInfo = new ProcessStartInfo(netcoredbg, arguments)
        {
            RedirectStandardOutput = true,
            RedirectStandardInput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            WindowStyle = ProcessWindowStyle.Hidden,
            CreateNoWindow = true
        }
    };
    process.Start();
    process.BeginOutputReadLine();
    process.BeginErrorReadLine();

    process.OutputDataReceived += (sender, outputArgs) =>
    {
        var data = outputArgs.Data;
        if (string.IsNullOrEmpty(data)) return;
        Console.WriteLine($"UNDERLYING::: {data}");
    };
    process.ErrorDataReceived += (sender, outputArgs) =>
    {
        var data = outputArgs.Data;
        if (string.IsNullOrEmpty(data)) return;
        Console.WriteLine($"UNDERLYING::: {data}");
    };

    Task.Factory.StartNew(() =>
    {
            while (true)
            {
                var line = Console.ReadLine();
                process.StandardInput.WriteLine(line);
            }
    });
    process.WaitForExit();
}
```

**Comment by kfrolov** [comment]
Please provide **full source** of the wrapper process.

**Comment by kfrolov** [comment]
I can confirm, that problem exists and can be reproduced without special "wrapper" process, with following shell command:
```
cat | bin/netcoredbg --interpreter=cli -ex "b Main" -ex run -ex step -- ~/bin/clr/corerun ~/test.dll
```

**Comment by kfrolov** [comment]
I have found the problem source: `cliprotocol.cpp` generates `SIGWINCH` every time when debugee is stopped. In normal condition, when input comes from the (pseudo)terminal, `liblinenoise` handles the case when `read()` syscall finished with `EINTR` (see `linenoise.cpp:2576`). But when input comes from a pipe (file, etc... no from the terminal), `liblinenoise` just calls `fgets` (see `linenoise.cpp:3252`) and not bothers about `EINTR`. So, `fgets` terminates with NULL, which is perceived as EOF (in `cliprotocol.cpp`, in command loop).

I think, solution is to stop generating `SIGWINCH` if input comes not from a terminal.  I have prepared #62 which fixes the issue.

**Comment by viewizard** [comment]
@Martin-Molinero could you please test #62?

**Comment by Martin-Molinero** [comment]
Hey! 
Can confirm the issue is solved by https://github.com/Samsung/netcoredbg/pull/62, thanks for that fast fix 🚀!

**Comment by viewizard** [comment]
@kfrolov @Martin-Molinero  I created PR in internal Samsung github with this cherry-picked commit. CI tests passed, waiting for reviewers. Should be in public upstream at next sync.

**Comment by viewizard** [comment]
Fixed in upstream.
