### ISSUE TITLE
What's the best way to debug unit tests?

### ISSUE THREAD

**Issue by aqez** [Samsung/netcoredbg#64]
Pretty much the title. I'd like to be able to step through our unit tests using netcoredbg if possible - what would the command line for that be like? Sorry if this has been asked or seems super basic - I couldn't find anything in issues.

**Comment by viewizard** [comment]
In case you can't start test inside debugger, you probably could add some `sleep` in test code and attach debugger during this sleep to the process. I usually do in this way in case some issue with netcoredbg during our functional tests execution, just add `sleep` in test and attach gdb to netcoredbg process for debugging.

**Comment by willat8** [comment]
I managed to get debugging unit tests working with the following:

```sh
VSTEST_HOST_DEBUG=1 dotnet test test/UnitTests/bin/Debug/net6.0/UnitTests.dll &
# Wait for the PID to be displayed, substitute as <pid> below
netcoredbg -ex "break src/App/Program.cs:50" --attach <pid>
```
Strangely I found this had to be done with the backgrounding (`&`) otherwise I just wasn't able to attach to the process.
