### ISSUE TITLE
No macOS build for 1.2.0-825

### ISSUE THREAD

**Issue by puremourning** [Samsung/netcoredbg#66]
Will there be a macOS binary supplied for the 1.2.0-825 release?

**Comment by viewizard** [comment]
No, we don't have macOS at this moment and CI still not operational.

**Comment by viewizard** [comment]
@puremourning macOS build added to release 2.0.0-895
We built and tested it on our CI, but could you please also test this macOS build?

**Comment by puremourning** [comment]
yes, sure. I'll update vimspector to use it and let its CI run too :)
