### ISSUE TITLE
How to set a launchprofile?

### ISSUE THREAD

**Issue by MikaelElkiaer** [Samsung/netcoredbg#68]
The `dotnet run` [command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run) has a parameter `--launch-profile` which can be set, referring to a profile defined in `Properties/launchSettings.json`. Can I somehow set this parameter when starting a program with netcoredbg?

**Comment by o-lek** [comment]
Hello, MikaelElkiaer!
I'm afraid, currently there is no way to pass any arguments to dotnet run command. You can start your debugging process as usual and then attach the netcoredbg to it.

**Comment by MikaelElkiaer** [comment]
Ok, was hoping to avoid this since I cannot find a way to wait for the debugger without adding some statement to my code.

**Comment by alpencolt** [comment]
@MikaelElkiaer we'll add this feature, but now you can write simple shell script which run your application, search pid of applications using `ps` and next attach NCDB. Its very fast and you'll lose only few milliseconds after start.
If you need some initial setup for debugger you can write such commands to text file and pass to debugger:
```
netcoredbg --attach <pid> --command=<command_file>
```

**Comment by MikaelElkiaer** [comment]
> @MikaelElkiaer we'll add this feature, but now you can write simple shell script which run your application, search pid of applications using `ps` and next attach NCDB. Its very fast and you'll lose only few milliseconds after start. If you need some initial setup for debugger you can write such commands to text file and pass to debugger:
> 
> ```
> netcoredbg --attach <pid> --command=<command_file>
> ```

Thank you, sounds good with both future prospects and current method.

**Comment by o-lek** [comment]
@MikaelElkiaer,
you can now set dotnet run parameters in 2 ways:
1. pass them as netcoredbg arguments:
    $>netcoredbg [netcoredbg params] [-- dotnet run [run params]] [-- [your_app_params]]
2. set them by set args command:
    ncdb> file dotnet
    ncdb> set args run [run params] [-- [your_app_params]]

**Comment by MikaelElkiaer** [comment]
@o-lek Awesome, thanks! When will it be released?

**Comment by o-lek** [comment]
@MikaelElkiaer,
It's already there. You can try it right now.

**Comment by MikaelElkiaer** [comment]
It seems to be working, awesome, thanks.

Just to sate my massive confusion? So this was possible all along? I mean, I don't see any relevant updates, anywhere...
