### ISSUE TITLE
Async methods support

### ISSUE THREAD

**Issue by Anakael** [Samsung/netcoredbg#74]
It seems like there is no support for async methods.

I have following code snippet:
```csharp
string Lol(Record rec)
{
    string a = rec.Lol;
    return a;
}

Task<string> LolAsyncWithoutAwait(Record rec)
{
    string a = rec.Lol;
    return Task.FromResult(a);
}

async Task<string> LolAsync(Record rec)
{
    string a = rec.Lol;
    await Task.Run(() => {});
    return a;
}


Record lol1 = new("lol");
Lol(lol1);
```
If I point BP in `Lol` or `LolAsyncWithoutAwait` methods I can see value of `a` and `rec` vars.
But if I call `LolAsync` with BP in it there is no vars to watching.

Netcoredbg version: 2.0.0-22
Frontend: nvim-dap + nvim-dap-ui

**Comment by alpencolt** [comment]
NCDB has async support, but it might be regression.
@viewizard could you check

**Comment by viewizard** [comment]
Since compiler reorganize user code during async method compilation, this could be the point. Will check this at monday.

**Comment by viewizard** [comment]
Support was added in last release. If you have any issues, please, open new issue.

**Comment by Anakael** [comment]
It works great, thank you!
