### ISSUE TITLE
Remote attach to netcoredbg process

### ISSUE THREAD

**Issue by C-SELLERS** [Samsung/netcoredbg#75]
## Issue Description ##
Heyo,

I am working on a project that requires a remote debug connection from one container running open vscode to another container running a dotnet 5 program. I'm attempting to use  [muhammadsammy/free-omnisharp-vscode](https://github.com/muhammadsammy/free-omnisharp-vscode) & [samsung/netcoredbg](https://github.com/Samsung/netcoredbg), since microsoft C# extension is proprietary and won't work with open vs code 😢. 

I have tried quite a few different ways of attempting to do this, but have hit quite a few roadblocks.
If anyone has some advice on this kind of setup please let me know. I am going to post this in both free-omnisharp-vscode & netcoredbg repos.

Here are my latest attempts

### Attempt 1
- Run the dotnet dll at launch of program container
- Use pipetransport in VS container to launch a script that creates an ssh connection to the program container and executes `netcoredbg --interpreter=vscode` 
Launch config
```
        {
            "name": "Attach Remote C#",
            "type": "coreclr",
            "request": "attach",
            "requireExactSource": false,
            "justMyCode": false,
            "processId":"",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "${workspaceFolder}/.vscode/connect.sh",
                "pipeArgs": [],
                "debuggerPath": "/QuantConnect/netcoredbg"
            }
        },
```

connect.sh
`ssh -o "StrictHostKeyChecking no" test@172.19.0.2 '/QuantConnect/netcoredbg --interpreter=vscode --log --engineLogging=/Log/log.txt --attach 91'` (Variations of this, with/without PID, with/without logging)

#### Output
 No PID Included:
```Operating system """ not supported```

Tweaking this a bit to do try logging I also see  ```Operating system "{Content Length: 56}" not supported``` 😕 

So it making the connection and starting netcoredbg but the debugger is having issues.

PID Included:
`{"seq":1,"body":{},"event":"initialized","type":"event"}stderr: Error: 0x80070057 Failed to attach to 91`

### Attempt 2
- Have program container start idle (interactive bash)
- Use pipetransport in VS container to launch a script that creates an ssh connection to the program container and executes '/QuantConnect/netcoredbg --interpreter=vscode -- /usr/bin/dotnet /Lean/Launcher/bin/Debug/QuantConnect.Lean.Launcher.dll'

#### Output

So this is interesting, because I see two different behaviors

1. Running locally (Official C# Extension); connects, launches program, debugger attaches, breaks on exception. 🤔 

Not really important though because its not my use case. The exception is probably because I am using official C# with netcoredbg ❌ 

2. Running in Open VS Code

```Operating system """ not supported``` 😢 

### Ideas
I noticed `netcoredbg` has a --server flag that would allow launching the process and then debugging through a port instead of requiring SSH, has anybody used this and had it work? I see in a VSCode configuration I can add "debugServer", but its just the port. 🤔 

Even trying this locally with an exposed port did not work as I would've hoped.

## Environment information ##

**VSCode version**: 1.62.3
**C# Extension**: 1.23.16

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.402/

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  5.0.402 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|muhammad-sammy|1.23.16|
|jupyter|ms-toolsai|2021.8.12|
|python|ms-python|2021.11.1422169775|;

</details>

**Comment by C-SELLERS** [comment]
Link to issue in other repo -> muhammadsammy/free-omnisharp-vscode#33

**Comment by viewizard** [comment]
IMO, you need start netcoredbg in "server" mode and interact by port from omnisharp side. But the point is:
https://github.com/OmniSharp/omnisharp-vscode/issues/3943
```The right way to solve this would be to add a new netcordbg (or whatever folks want to call it) debug adapter type.```
I don't see how you could work in proper way with omnisharp's adapter that don't support netcoredbg at all.

**Comment by C-SELLERS** [comment]
I figured out this guy

```Operating system """ not supported```


I was using a bash script as my pipetransport to set up the connection to netcoredbg on the remote machine, but the way the debugger extension (free-omnisharp) would attempt to use my pipetransport, is to send commands to read the processes on the remote. Because my pipetransport was not really an open line to the remote machine it would break attempting to read the OS and then the processes. Failing out.

Now that I am able to dig deeper into this by debugging the extension I am just going to close this issue out here.
