### ISSUE TITLE
Failed command 'configurationDone' : 0x80070057

### ISSUE THREAD

**Issue by C-SELLERS** [Samsung/netcoredbg#77]
Running into an issue with 'configurationDone' request from VSCode Debug Adapter.

When running a remote debug connection where a DotNet 5 program is running on remote computer, and NetCoreDbg is running locally and attaching to process. I got this error message.

```
Failed command 'configurationDone' : 0x80070057
```

Here is the complete netcoredbg engine log

```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request","seq":1}
<- (E) {"seq":1,"body":{"capabilities":{"exceptionBreakpointFilters":[{"filter":"user-unhandled","label":"user-unhandled"},{"filter":"all","label":"all"}],"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsExceptionFilterOptions":true,"supportsExceptionInfoRequest":true,"supportsExceptionOptions":false,"supportsFunctionBreakpoints":true,"supportsSetVariable":true,"supportsTerminateRequest":true}},"event":"capabilities","type":"event"}
<- (E) {"seq":2,"body":{},"event":"initialized","type":"event"}
<- (R) {"seq":3,"body":{"exceptionBreakpointFilters":[{"filter":"user-unhandled","label":"user-unhandled"},{"filter":"all","label":"all"}],"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsExceptionFilterOptions":true,"supportsExceptionInfoRequest":true,"supportsExceptionOptions":false,"supportsFunctionBreakpoints":true,"supportsSetVariable":true,"supportsTerminateRequest":true},"command":"initialize","request_seq":1,"success":true,"type":"response"}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Main.cs","path":"/mnt/c/Dev/QuantConnect/Repos/WorkFiles/vscode11/testproject/Main.cs"},"lines":[38,39],"breakpoints":[{"line":38},{"line":39}],"sourceModified":false},"type":"request","seq":2}
<- (R) {"seq":4,"body":{"breakpoints":[{"id":1,"line":38,"message":"The breakpoint is pending and will be resolved when debugging starts.","verified":false},{"id":2,"line":39,"message":"The breakpoint is pending and will be resolved when debugging starts.","verified":false}]},"command":"setBreakpoints","request_seq":2,"success":true,"type":"response"}
-> (C) {"command":"attach","arguments":{"name":"Attach Remote C#","type":"coreclr","request":"attach","requireExactSource":false,"justMyCode":false,"pipeTransport":{"pipeProgram":"sshpass","pipeArgs":["-p","test","ssh","-T","test@0.0.0.0","-p 2222"],"debuggerPath":"/QuantConnect/netcoredbg/netcoredbg","pipeCwd":"/mnt/c/Dev/QuantConnect/Repos/WorkFiles/vscode11","quoteArgs":true},"logging":{"engineLogging":true,"browserStdOut":true,"elapsedTiming":true,"exceptions":true,"moduleLoad":true,"processExit":true,"programOutput":true,"threadExit":true},"__configurationTarget":5,"processId":"493","__sessionId":"1423a5e6-1c77-4a52-934b-4c9297319af6"},"type":"request","seq":3}
<- (R) {"seq":5,"body":{},"command":"attach","request_seq":3,"success":true,"type":"response"}
-> (C) {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
<- (R) {"seq":6,"body":{"breakpoints":[]},"command":"setFunctionBreakpoints","request_seq":4,"success":true,"type":"response"}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[]},"type":"request","seq":5}
<- (R) {"seq":7,"body":{},"command":"setExceptionBreakpoints","request_seq":5,"success":true,"type":"response"}
-> (C) {"command":"configurationDone","type":"request","seq":6}
<- (R) {"seq":8,"command":"configurationDone","message":"Failed command 'configurationDone' : 0x80070057","request_seq":6,"success":false,"type":"response"}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}
<- (R) {"seq":9,"body":{},"command":"disconnect","request_seq":7,"success":true,"type":"response"}
```

**Comment by C-SELLERS** [comment]
I believe this is the same issue as this one from the free-omnisharp-vscode repo

muhammadsammy/free-omnisharp-vscode#9

**Comment by viewizard** [comment]
0x80070057 mean E_INVALIDARG.
```
-> (C) {"command":"attach","arguments":{"name":"Attach Remote C#","type":"coreclr","request":"attach","requireExactSource":false,"justMyCode":false,"pipeTransport":{"pipeProgram":"sshpass","pipeArgs":["-p","test","ssh","-T","test@0.0.0.0","-p 2222"],"debuggerPath":"/QuantConnect/netcoredbg/netcoredbg","pipeCwd":"/mnt/c/Dev/QuantConnect/Repos/WorkFiles/vscode11","quoteArgs":true},"logging":{"engineLogging":true,"browserStdOut":true,"elapsedTiming":true,"exceptions":true,"moduleLoad":true,"processExit":true,"programOutput":true,"threadExit":true},"__configurationTarget":5,"processId":"493","__sessionId":"1423a5e6-1c77-4a52-934b-4c9297319af6"},"type":"request","seq":3}
```
NetcoreDBG don't support "pipeTransport" for sure. Here is "attach" implementation for VSCode protocol:
https://github.com/Samsung/netcoredbg/blob/2de336c9496f6b3e8817ed19c70a9d957b8afc43/src/protocols/vscodeprotocol.cpp#L704-L715

Since you provide "processId" looks like E_INVALIDARG you receive at "configurationDone" command in replay from here:
https://github.com/Samsung/netcoredbg/blob/2de336c9496f6b3e8817ed19c70a9d957b8afc43/src/debugger/manageddebugger.cpp#L754

Check, that you PID is managed process, looks like dbgshim (see `EnumerateCLRs()` call) can't find libcoreclr.so inside process with this PID:
https://github.com/Samsung/netcoredbg/blob/2de336c9496f6b3e8817ed19c70a9d957b8afc43/src/debugger/manageddebugger.cpp#L407-L463

**Comment by C-SELLERS** [comment]
Thank you for your speedy reply, will look into this and follow up 👍🏽

**Comment by C-SELLERS** [comment]
>NetcoreDBG don't support "pipeTransport" for sure. Here is "attach" implementation for VSCode protocol:

For sure. That is really for the extension in VSCode to setup a connection to other remote machine which it will send and receive messages through. 

It still contains the arg for the PID as `processId` so I don't think that's an issue, like you suggested 👍🏽 


>Check, that you PID is managed process, looks like dbgshim (see EnumerateCLRs() call) can't find libcoreclr.so inside process with this PID

Hmm 🤔 The PID is a definitely the dotnet process I used to start the program.

**Comment by viewizard** [comment]
Hmm... just to be sure, you start NetCoreDbg on remote PC, start managed process on remote PC and attach debugger to process (debugger and debuggee process on same PC). ```... and NetCoreDbg is running locally and attaching to process.``` mean you start NetCoreDbg on remote PC, right?

**Comment by C-SELLERS** [comment]
Hmmmm, this is actually hard to say exactly what the arrangement is and I think you are bringing up a good point.

Something I am noticing with the original C# extension is that it apparently uses `vsdbg-ui` on the local machine to connect to `vsdbg` on the remote machine.

For the free omnisharp version it appears that it may actually launch the `netcoredbg` locally and attach that way? :/ Seems odd really. I am digging into whether or not it actually starts `netcoredbg` on the remote machine (I believe it does). Its fishy that it starts it on the local machine at all though 🤔

**Comment by C-SELLERS** [comment]
Hey so I got further into it and have some findings.

I believe the `free-omnisharp` extension is attempting to run `netcoredbg` locally and connect to the remote process which is problematic. Questions is, should this work?

Further exploration on making an extension that would work with remote debugging was very interesting and I found a solution that leverages the `--server` setup which launches `netcoredbg` on the remote machine and then uses `vscode.DebugAdapterServer()` as means to communicate with the debugger (`netcoredbg`). This works, although there was some weirdness with using an attach request vs a launch. 

Heres my notes:
```
C# Debugging a remote `dotnet` process with `netcoredbg`

cs-netcoredbg extension: (New custom extension)
	- "launch" <- Very nice and simple, no PID required ✔
		○ Requires remote Lean process is started with netcoredbg in server mode (Default port is 4711)
			§ /QuantConnect/netcoredbg/netcoredbg --interpreter=vscode --log --engineLogging=/Log/log.txt --server -- /usr/bin/dotnet /Lean/Launcher/bin/Debug/QuantConnect.Lean.Launcher.dll
	- "attach" ✔
		○ Requires lean started independently
			§ dotnet ./QuantConnect.Lean.Launcher.dll
		○ Start netcoredbg is server mode (4711)
			§ /QuantConnect/netcoredbg/netcoredbg --interpreter=vscode --log --engineLogging=/Log/log.txt --server
		○ Get PID of lean, add as parameter to "attach" configuration in .vscode/launch.json
		○ *NOTES: MUST RUN LEAN AND NETCOREDBG FROM SAME USER!!!


free-omnisharp: ❌
	- Does not work for remote debugging; reason appears to be it launches `netcoredbg` locally to attach to remote process ❌
		○ Could be related to issue above; lean and netcoredbg need to be run from same user.
		○ Could also be an unallowed arrangement.
			§ Official VS Code uses `vsdbg-ui` to connect to `vsdbg` on remote which is debugging the program
			§ Netcoredbg appears to just attach directly to remote process

			
Overall Notes:
-  make sure to run this in lean bin for composer to load dlls.
```

**Comment by C-SELLERS** [comment]
Going to close this as of now. 

Depending on how my team moves forward I may even release a remote-netcoredbg debug extension for VS Code that simply hooks vscode to the netcoredbg in server mode. Will likely be very basic but could helpful for others that have this use case.

**Comment by MikaelElkiaer** [comment]
@C-SELLERS This is super interesting for me, but for Neovim, not VSCode.
The approach should be the same, as something like [nvim-dap](github.com/mfussenegger/nvim-dap) can also utilize VSCode's launch.json, but it would be nice if any solution did not become too VSCode-centric.
