### ISSUE TITLE
Does someone running netcoredbg on Win10 x86 OS?

### ISSUE THREAD

**Issue by fenixjiang** [Samsung/netcoredbg#79]
Here is the problem I compiled under win10 x86 os - https://github.com/Samsung/netcoredbg/issues/76.
Does anyone have a similar problem?

**Comment by fenixjiang** [comment]
Here is the problem I compiled under win10 x86 os - https://github.com/Samsung/netcoredbg/issues/76.
Does anyone have a similar problem?

**Comment by viewizard** [comment]
Fixed in upstream. Windows 10 x86 build and work now.
