### ISSUE TITLE
Is it possible to debug a dotnet core 3.1 webapi project with "dotnet run" + xxx.csproj?

### ISSUE THREAD

**Issue by lubyrex** [Samsung/netcoredbg#87]
as the title has stated, running dotnet xxx.dll breaks on my machine somehow, whereas running dotnet run xxx.csproj works. Is it possible for netcoredbg to debug using dotnet run?

**Comment by viewizard** [comment]
No, since `dotnet` is managed application itself and debugger will start debug session for `dotnet` instead of you application.
