### ISSUE TITLE
Building the code for Visual Studio 17 2022

### ISSUE THREAD

**Issue by awa5114** [Samsung/netcoredbg#93]
I tried building the code for Visual Studio 17 2022 and got the following error:

```
PS> cmake ../ -G "Visual Studio 17 2022"

CMake Error: Error: generator : Visual Studio 17 2022
Does not match the generator used previously: Visual Studio 16 2019
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

At this point in time are we only able to build the code using 2019? Or should 2022 also work?

**Comment by viewizard** [comment]
> CMake Error: Error: generator : Visual Studio 17 2022
> Does not match the generator used previously: Visual Studio 16 2019

You need build from another build folder (use build_2022 for VS 2022 and build_2019 for VS 2019, for example) or clean all previous files created by VS 2019. You can't mix VS2019 and VS2022 build files.

**Comment by awa5114** [comment]
Thanks.
