### ISSUE TITLE
Building the source code: Missing an argument for parameter 'Architecture'. 

### ISSUE THREAD

**Issue by awa5114** [Samsung/netcoredbg#94]
I tried to build the source using CMake as follows:

`PS> cmake ../ -G "Visual Studio 17 2022"`

Here's the log output:
```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.32.31329.0
-- The CXX compiler identification is MSVC 19.32.31329.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.36.1.windows.1")
Cloning into 'C:/Users/aa/Desktop/TEMP/netcoredbg/.coreclr'...
remote: Enumerating objects: 34914, done.
remote: Counting objects: 100% (34914/34914), done.
remote: Compressing objects: 100% (18035/18035), done.
remote: Total 34914 (delta 19493), reused 23908 (delta 16613), pack-reused 0
Receiving objects: 100% (34914/34914), 41.42 MiB | 7.71 MiB/s, done.
Resolving deltas: 100% (19493/19493), done.
Updating files: 100% (30146/30146), done.
C:\Users\aa\Desktop\TEMP\netcoredbg\build\dotnet-install.ps1 : Missing an argument for parameter 'Architecture'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo          : InvalidArgument: (:) [dotnet-install.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument,dotnet-install.ps1

CMake Error at fetchdeps.cmake:60 (message):
  Fatal error when installing dotnet
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/aa/Desktop/TEMP/netcoredbg/build/CMakeFiles/CMakeOutput.log".
```

Not sure what I'm doing wrong here. Any assistance would be welcome. Thanks.

**Comment by awa5114** [comment]
That works, thanks.

**Comment by viewizard** [comment]
@awa5114 I already added this fix into our internal dev repo when tested this fix before wrote answer, will be in public upstream at next sync.

**Comment by awa5114** [comment]
@viewizard I was under the impression that this repo was under an MIT license. Where is this "internal dev repo" you mention? Is that just your personal fork?

**Comment by viewizard** [comment]
We have internal Samsung git repo for development (I am Samsung employee). When code have some consistant state, we sync it with public repo. Plus, since we stay with same commits hashes in internal and public repo, you could be sure you see same code as I am in internal repo. :-)

**Comment by awa5114** [comment]
Ok. Do you accept contributions from the community as well? When they haven't been implemented by a Samsung employee and are viable changes?

**Comment by viewizard** [comment]
Sure, we accept contributions, but instead of merge PR in public repo directly, we move PR's commits into internal repo first, check code, test all this changes with our CI, and after that (at sync) close initial PR in public repo.
As you could see, at last sync we also have commit from public PR: https://github.com/Samsung/netcoredbg/pull/86 https://github.com/Samsung/netcoredbg/commit/cd606fad353894908bfee183f695c72a264ef939
