### ISSUE TITLE
Async stepper:  does not step over from the last line of task.

### ISSUE THREAD

**Issue by fenixjiang** [Samsung/netcoredbg#97]
StepOver is failed in the following example:

    static void Main(string[] args)
    {
        Task.Run((Action)( async () =>
        {
            await Task.Yield();
        }));

        Console.ReadLine();
    }
    
Set breakpoint at `await Task.Yield()` , and step over to the last line of task. Continue step over will failed. ncdb ouput:

    ->(C)    {"seq"：29， “type":"request", "command":”next", "argument":{"threadId:27568}}
    <-(R)    {"command":"next", "message":"Failed command 'next' : 0x80004005", "request_seq":29,"seq":47,"success":false,"type":"response"}

debugger found [SetNotificationForWaitCompletion](https://github.com/Samsung/netcoredbg/blob/master/src/debugger/stepper_async.cpp#L290) failed. Cannot find `SetNotificationForWaitCompletion`

But it's work if my `Task.Run` like this:

    static void Main(string[] args)
    {
        Task.Run(( async () =>    // without Action cast
        {
            await Task.Yield();
        }));

        Console.ReadLine();
    }

**Comment by alpencolt** [comment]
Thanks, we'll check. Looks like a bug in async stepping

**Comment by viewizard** [comment]
Fixed in commit https://github.com/Samsung/netcoredbg/commit/84b8f789e065ec26b0e3d421ec82fe5bf40b2746
