### ISSUE TITLE
How to debug .NET unit test

### ISSUE THREAD

**Issue by lillo42** [Samsung/netcoredbg#99]
Hi folks,

I don't know if here is the right place to ask it

How can I debug an unit test using netcoredbg with--interpreter=vscode?

I'm trying to nvim with netcoredbg, debug application is fine but I'm not find anyway debug unit test

**Comment by alpencolt** [comment]
`dotnet test` run new process and NCDB doesn't handle system calls and keep debugging `dotnet` process.
But you may attach to needed test if you know it's PID. Check there https://github.com/Samsung/netcoredbg/issues/64#issuecomment-846566264
